'use strict';
function findBossFree(e){let radius=e.radius||46;if(!isBlocked(e.x,e.y,radius))return true;let ox=e.x,oy=e.y;for(let distance=32;distance<=768;distance+=32)for(let i=0;i<32;i++){let a=i*Math.PI/16,x=ox+Math.cos(a)*distance,y=oy+Math.sin(a)*distance;if(!isBlocked(x,y,radius)){e.x=x;e.y=y;e.bossPath=null;return true}}return false}
function bossLineClear(e,x,y,obstacles){let distance=Math.hypot(x-e.x,y-e.y),steps=Math.ceil(distance/16);for(let i=1;i<=steps;i++)if(isBlocked(e.x+(x-e.x)*i/steps,e.y+(y-e.y)*i/steps,e.radius,obstacles))return false;return true}
function bossPath(e,dx,dy){let cell=48,bound=13,obstacles=nearbyWorld(e.x,e.y,cell*bound+100).obstacles,d=Math.hypot(dx,dy)||1,target={x:dx/d*Math.min(d,cell*(bound-2)),y:dy/d*Math.min(d,cell*(bound-2))},gx=Math.round(target.x/cell),gy=Math.round(target.y/cell),key=(x,y)=>x+','+y,open=[{x:0,y:0,g:0,f:0}],nodes=new Map([[key(0,0),open[0]]]),closed=new Set(),best=open[0],bestDistance=Infinity;for(let iteration=0;open.length&&iteration<700;iteration++){open.sort((a,b)=>a.f-b.f);let current=open.shift(),k=key(current.x,current.y);if(closed.has(k))continue;closed.add(k);let distance=Math.hypot(current.x-gx,current.y-gy);if(distance<bestDistance){best=current;bestDistance=distance}if(distance<1.1)break;for(let [sx,sy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){let x=current.x+sx,y=current.y+sy,nk=key(x,y);if(Math.abs(x)>bound||Math.abs(y)>bound||closed.has(nk))continue;let nx=e.x+x*cell,ny=e.y+y*cell;if(isBlocked(nx,ny,e.radius,obstacles)||sx&&sy&&(isBlocked(e.x+current.x*cell+sx*cell,e.y+current.y*cell,e.radius,obstacles)||isBlocked(e.x+current.x*cell,e.y+current.y*cell+sy*cell,e.radius,obstacles)))continue;let g=current.g+Math.hypot(sx,sy),old=nodes.get(nk);if(old&&old.g<=g)continue;let node={x,y,g,f:g+Math.hypot(x-gx,y-gy),parent:current};nodes.set(nk,node);open.push(node)}}let route=[];for(let node=best;node.parent;node=node.parent)route.push({x:e.x+node.x*cell,y:e.y+node.y*cell});return route.reverse()}
const routeSteer=steerEnemy;steerEnemy=function(e,dx,dy,dt){if(e.aoeWind>0)return 0;if(e.type!=='boss')return routeSteer(e,dx,dy,dt);if(!findBossFree(e))return 0;let obstacles=nearbyWorld(e.x,e.y,Math.min(Math.hypot(dx,dy),1600)+e.radius+70).obstacles,point={x:e.x+dx,y:e.y+dy};if(!bossLineClear(e,point.x,point.y,obstacles)){e.pathTime=(e.pathTime||0)-dt;if(e.pathTime<=0||!Array.isArray(e.bossPath)){e.bossPath=bossPath(e,dx,dy);e.pathTime=.8}while(e.bossPath?.length&&Math.hypot(e.bossPath[0].x-e.x,e.bossPath[0].y-e.y)<8)e.bossPath.shift();point=e.bossPath?.[0]||{x:e.x,y:e.y}}else e.bossPath=null;let vx=point.x-e.x,vy=point.y-e.y,d=Math.hypot(vx,vy)||1,step=Math.min(d,e.speed*dt),moved=moveActor(e,vx/d*step,vy/d*step,e.radius);if(moved<.01){e.pathTime=Math.min(e.pathTime||.2,.2);e.stuckTime=(e.stuckTime||0)+dt;if(e.stuckTime>3){let distance=Math.hypot(dx,dy)||1;for(let step=80;step<=400;step+=40){let nx=e.x+dx/distance*step,ny=e.y+dy/distance*step;if(!isBlocked(nx,ny,e.radius)){particles(e.x,e.y,'#dec28b',8);e.x=nx;e.y=ny;e.bossPath=null;e.stuckTime=0;break}}}}else e.stuckTime=0;return moved};
function nextRarity(r){return RARITIES[RARITIES.findIndex(t=>t.id===r.id)+1]}
const standardChoices=upgradeChoices;upgradeChoices=function(s){let normal=standardChoices(s).filter(u=>!u.reward),promotions=DATA.upgrades.filter(u=>!u.weapon&&!u.armor&&learnedRarity(s,u.id)&&(s.upgrades[u.id]||0)>=upgradeLimit(s,u)&&nextRarity(learnedRarity(s,u.id))).map(u=>({...u,promotion:true,rarity:nextRarity(learnedRarity(s,u.id))}));if(promotions.length){let promotion=promotions[Math.floor(Math.random()*promotions.length)];if(normal.length<3)normal.push(promotion);else if(Math.random()<.65)normal[Math.floor(Math.random()*3)]=promotion}for(let reward of CAMP_REWARDS){if(normal.length>=3)break;normal.push({...reward,reward:true})}return normal};
const oldRarityDescription=rarityDescription;rarityDescription=function(u){let f=u.rarity?.factor||1;if(u.id==='regen')return `Восстановление +${(.6*f).toFixed(2)} HP в секунду.`;if(u.id==='magnet')return `Радиус притяжения опыта +${Math.round(20*f)}%.`;if(u.id==='focus')return `Ожидание активной способности −${Math.round(3*f)} п.п. (максимум 60%).`;if(u.id==='skin')return `Защита +${(2*f).toFixed(1)} п.п. (общий максимум 70%).`;if(u.id==='precision')return `Шанс двойного урона +${Math.round(2*f)} п.п. (максимум 60%).`;if(u.id==='multi'&&state?.multi>=6)return `Снарядов уже 6. Урон +${Math.round(8*f)}%.`;return oldRarityDescription(u)};
const adventureChoose=choose;choose=function(u){if(!state.pending)return;let s=state,spec=DATA.upgrades.find(t=>t.id===u.id);if(u.promotion){let current=learnedRarity(s,u.id),next=current&&nextRarity(current);if(!spec||spec.weapon||spec.armor||!next||(s.upgrades[u.id]||0)<UPGRADE_LIMITS[current.id]){offer();return}s.upgradeHistory??={};s.upgradeHistory[u.id]??=[];s.upgradeHistory[u.id].push({rarity:current.id,levels:s.upgrades[u.id]});s.upgradeRarities[u.id]=next.id;s.upgrades[u.id]=0;s.pending--;saveRun();offer();return}if(['regen','magnet','focus','skin','precision'].includes(u.id)||u.id==='multi'&&s.multi>=6){let rarity=learnedRarity(s,u.id)||u.rarity||RARITIES[0];if(!spec||(s.upgrades[u.id]||0)>=UPGRADE_LIMITS[rarity.id]){offer();return}s.upgradeRarities[u.id]=rarity.id;s.upgrades[u.id]=(s.upgrades[u.id]||0)+1;let f=rarity.factor;if(u.id==='regen')s.regen=(s.regen||0)+.6*f;if(u.id==='magnet')s.magnetBonus=(s.magnetBonus||0)+.2*f;if(u.id==='focus')s.focusBonus=Math.min(.6,(s.focusBonus||0)+.03*f);if(u.id==='skin')s.skinBoost=Math.min(.7,(s.skinBoost||0)+.02*f);if(u.id==='precision')s.critChance=Math.min(.6,(s.critChance||0)+.02*f);if(u.id==='multi')s.damage*=1+.08*f;s.pending--;saveRun();offer();return}adventureChoose(u)};
// Projectile cap does not prevent improving the damage of the multi-shot talent.
const cappedAvailable=availableUpgrade;availableUpgrade=function(s,u){if(u.id==='multi'&&s.multi>=6)return(s.upgrades[u.id]||0)<upgradeLimit(s,u);return cappedAvailable(s,u)};
const adventureState=newState;newState=function(){let s=adventureState();s.adventureVersion=12;s.upgradeHistory={};return s};
const adventureMigrate=migrateState;migrateState=function(s){adventureMigrate(s);s.upgradeHistory??={};for(let id of ['regen','magnetBonus','focusBonus','skinBoost','critChance'])s[id]=s[id]||0;if(s.adventureVersion!==12){let old=s.nextXp||1,progress=s.xp/old;s.nextXp=xpForLevel(s.level);s.xp=Math.floor(progress*s.nextXp);s.adventureVersion=12}for(let e of s.enemies)if(e.type==='boss')findBossFree(e)};
function skillSummary(s){let items=DATA.upgrades.filter(u=>(s.upgrades[u.id]||0)>0||(s.upgradeHistory?.[u.id]?.length||0)>0);return `<section class="pauseSkills"><h3>Твои навыки</h3><p>Активная: ${DATA.heroes[s.hero].active.name}</p>${items.length?items.map(u=>{let r=learnedRarity(s,u.id)||RARITIES[0],count=s.upgrades[u.id]||0,total=(s.upgradeHistory?.[u.id]||[]).reduce((sum,h)=>sum+h.levels,0)+count;return `<div class="pauseSkill"><b>${u.name}</b><span style="color:${r.color}">${r.name} · ${count}/${UPGRADE_LIMITS[r.id]}${count>=UPGRADE_LIMITS[r.id]?' · МАКСИМУМ':''}</span><small>Всего улучшений: ${total}</small></div>`}).join(''):'<p>Таланты пока не выбраны.</p>'}</section>`}
const adventurePause=pause;pause=function(){let wasPlaying=mode==='playing';adventurePause();if(wasPlaying&&mode==='paused')$('dialog').insertAdjacentHTML('beforeend',skillSummary(state))};
const adventureUpdate=update;update=function(dt){let s=state,ed=worldDelta(dt);s.areaWaveCooldown=Math.max(0,(s.areaWaveCooldown||0)-ed);for(let e of s.enemies){if(e.type==='boss')findBossFree(e);if(!e.aoe||e.hp<=0||ed===0)continue;e.areaTimer=(e.areaTimer??(6+Math.random()*4))-ed;e.aoeWind=Math.max(0,(e.aoeWind||0)-ed);if(e.areaTimer<=0&&s.areaWaveCooldown<=0){let target=netHost()?closestParty(e.x,e.y):s;if(target&&Math.hypot(target.x-e.x,target.y-e.y)<500){bossZone(e,target.x,target.y,60,.9,THEMES[e.theme].trap);e.aoeWind=.9;e.attackAnim=.3;e.areaTimer=difficulty().id==='hard'?7:9;s.areaWaveCooldown=1.8}}}adventureUpdate(dt);if(mode!=='dead'&&!s.down)s.hp=Math.min(s.maxHp,s.hp+(s.regen||0)*dt)};
const indicatorDraw=draw;draw=function(){indicatorDraw();if(!state)return;let b=state.enemies.find(e=>e.type==='boss'&&e.hp>0);if(!b)return;let dx=b.x-state.x,dy=b.y-state.y,a=Math.atan2(dy,dx),bx=W/2+dx,by=H/2+dy,outside=bx<60||bx>W-60||by<80||by>H-85;ctx.save();ctx.fillStyle='#f1cd87';ctx.strokeStyle='#f1cd87';ctx.lineWidth=2;if(outside){let extent=Math.min((W/2-65)/(Math.abs(Math.cos(a))||.001),(H/2-100)/(Math.abs(Math.sin(a))||.001)),x=W/2+Math.cos(a)*extent,y=H/2+Math.sin(a)*extent;ctx.translate(x,y);ctx.rotate(a);ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-8,-9);ctx.lineTo(-4,0);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.rotate(-a);ctx.textAlign='center';ctx.font='bold 11px Arial';ctx.fillText('БОСС · '+Math.round(Math.hypot(dx,dy)/10)+' м',0,25)}else{ctx.beginPath();ctx.arc(bx,by, b.radius+9,0,Math.PI*2);ctx.stroke()}ctx.restore()};
// The touchscreen pause button must resolve the expanded pause handler.
$('pauseBtn').onclick=()=>pause();
