'use strict';
let heroAnimationImage=new Image(),heroAnimationAtlas=null,environmentImage=new Image(),environmentAtlas=null,sorcererImage=new Image(),sorcererAtlas=null;
function transparentAtlas(img){let c=document.createElement('canvas');c.width=img.width;c.height=img.height;let ac=c.getContext('2d');ac.drawImage(img,0,0);try{let pixels=ac.getImageData(0,0,img.width,img.height);for(let i=0;i<pixels.data.length;i+=4){if(Math.max(pixels.data[i],pixels.data[i+1],pixels.data[i+2])<28)pixels.data[i+3]=0}ac.putImageData(pixels,0,0)}catch{}return c}
function animatedHeroSprite(c,hero,frame,attack,x,y,size){if(hero===3&&sorcererAtlas){let sw=sorcererAtlas.width/4,sy=attack?655:75,sh=attack?490:470,scale=size/470,sx=frame*sw,cw=sw,offset=0;if(attack&&frame===2)cw=365;if(attack&&frame===3){offset=65;sx+=offset;cw-=offset}c.drawImage(sorcererAtlas,sx,sy,cw,sh,x-sw*scale/2+offset*scale,y-sh*scale/2,cw*scale,sh*scale);return}if(hero===3){c.fillStyle="#d1c4ed";c.fillRect(x-size*.12,y-size*.15,size*.24,size*.4);return}if(heroAnimationAtlas){let row=hero===0?(attack?1:0):hero+1,sw=heroAnimationAtlas.width/4,band=DATA.animationRows[row],sh=band[1],dh=size*sh/sw;let sx=frame*sw,clipWidth=sw,offset=0;if(row===1&&frame===2)clipWidth=353;if(row===1&&frame===3){offset=43;sx+=offset;clipWidth-=offset}c.drawImage(heroAnimationAtlas,sx,band[0],clipWidth,sh,x-size/2+offset*size/sw,y-dh/2,clipWidth*size/sw,dh)}else sprite(c,hero,x,y,size)}
function weaponKind(s=state){return s.weapon==='Кибер-пистолет'?'gun':s.weapon==='Когти лунной крови'?'claws':s.weapon==='Фиолетовая пустота'?'violet':/лук/i.test(s.weapon)?'bow':/посох/i.test(s.weapon)?'staff':'daggers'}
function drawWeapon(x,y,angle,kind,progress,enemy=false){if(progress<=0)return;let c=ctx,p=Math.max(0,Math.min(1,progress/.3)),recoil=Math.sin((1-p)*Math.PI);c.save();c.translate(x,y);c.rotate(angle);c.lineCap='round';if(kind==='violet'){c.shadowBlur=18;c.shadowColor='#aa73ec';ellipse(c,18+recoil*4,0,7+p*5,7+p*5,'#b88cec');c.shadowBlur=0;c.strokeStyle='#dbbeff';c.lineWidth=1.5;c.beginPath();c.arc(18,0,12+recoil*5,-1.4,1.4);c.stroke();ellipse(c,18,0,3,3,'#f4e9ff')}else if(kind==='bow'){c.strokeStyle=enemy?'#e6a8a0':'#d9c08a';c.lineWidth=2;c.beginPath();c.arc(13-recoil*3,0,13,-1.08,1.08);c.stroke();c.strokeStyle='#eee4bb';c.lineWidth=1;c.beginPath();c.moveTo(19,-11);c.lineTo(10-recoil*8,0);c.lineTo(19,11);c.stroke();c.beginPath();c.moveTo(5-recoil*5,0);c.lineTo(26,0);c.stroke()}else if(kind==='staff'){c.strokeStyle='#b7a67b';c.lineWidth=3;c.beginPath();c.moveTo(3,10);c.lineTo(19-recoil*5,-7);c.stroke();c.shadowBlur=16;c.shadowColor=enemy?'#eaa188':'#a0d9ef';ellipse(c,19-recoil*5,-7,4+p*3,4+p*3,enemy?'#f0a285':'#b9e7fb');c.shadowBlur=0;c.strokeStyle=enemy?'#de876a90':'#a6dcea90';c.lineWidth=2;c.beginPath();c.arc(0,0,21+recoil*12,-.65,.65);c.stroke()}else{c.rotate(-1.1+recoil*2.2);c.strokeStyle=enemy?'#e5aaa3':'#d9dcea';c.lineWidth=3;c.beginPath();c.moveTo(8,-5);c.lineTo(27,-5);c.moveTo(8,6);c.lineTo(22,6);c.stroke();c.globalAlpha=p*.65;c.strokeStyle=enemy?'#df7770':'#c6a1e0';c.lineWidth=5;c.beginPath();c.arc(0,0,29,-.8,.8);c.stroke()}c.restore()}
function drawHero(){let s=state,moving=s.moving,kind=weaponKind(),attack=(s.attackAnim||0)>0,attackFrame=Math.min(3,Math.floor((.3-(s.attackAnim||0))/.075)),frame=attack&&((s.hero===0&&kind==='bow')||(s.hero===3&&kind==='violet'))?attackFrame:moving?Math.floor((s.walkClock||0)*9)%4:0,walk=Math.sin((s.walkClock||0)*Math.PI*4),facing=s.aimAngle||0;ctx.save();ctx.globalAlpha=s.down?.3:s.invuln>0&&Math.floor(s.time*15)%2?.45:1;ellipse(ctx,s.x,s.y+19,17,6,'#0007');ctx.translate(s.x,s.y);ctx.scale(Math.cos(facing)<0?-1:1,1);ctx.rotate(moving?walk*.018:0);let recoil=attack?Math.sin((1-s.attackAnim/.3)*Math.PI)*2:0;animatedHeroSprite(ctx,s.hero,frame,attack&&(kind==='bow'||kind==='violet'),-recoil, moving?Math.abs(walk)*-1.4:0,74);ctx.restore();drawWeapon(s.x,s.y,facing,kind,s.attackAnim||0);if(s.hero===1){ctx.save();ctx.globalAlpha=.18+Math.sin(s.time*3)*.04;ctx.strokeStyle='#83bdd9';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(s.x,s.y+14,20,7,0,0,Math.PI*2);ctx.stroke();ctx.restore()}}
function drawEnemy(e){let size=e.radius*3,clock=e.walkClock||0,walk=Math.sin(clock*10+e.phase),att=e.attackWind>0||e.attackAnim>0;ctx.save();ellipse(ctx,e.x,e.y+size*.27,e.radius,e.radius*.4,'#0005');ctx.translate(e.x,e.y);if(Math.cos(e.angle||0)<0)ctx.scale(-1,1);if(e.type==='mini'){ctx.scale(1+walk*.13,1-walk*.1)}else{ctx.rotate(walk*(e.type==='boss'?.023:.05));ctx.scale(1+walk*.018,1-walk*.028)}let recoil=att?Math.sin(state.time*20+e.phase)*2:0;if(e.hitAnim>0){ctx.globalAlpha=.58+Math.sin(state.time*45)*.2}sprite(ctx,e.sprite,recoil,e.type==='mini'?Math.sin(state.time*6+e.phase)*4:Math.abs(walk)*-1.8,size);ctx.restore();if(e.attackWind>0){ctx.save();ctx.strokeStyle='#eabb8690';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.radius+7,-Math.PI/2,-Math.PI/2+Math.PI*2*(1-e.attackWind/.38));ctx.stroke();ctx.restore()}if(e.type==='normal'||e.type==='rare'){drawWeapon(e.x,e.y,e.angle||0,'daggers',e.attackAnim||0,true)}else if(e.type==='boss'){drawWeapon(e.x,e.y,e.angle||0,'staff',e.attackAnim||0,true);if((e.shot||0)<.6){ctx.save();ctx.strokeStyle='#e4a49780';ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.radius+8+Math.sin(state.time*20)*3,0,Math.PI*2);ctx.stroke();ctx.restore()}}else if(e.attackAnim>0){ctx.strokeStyle='#c99be1';ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,e.radius+5,e.angle-.7,e.angle+.7);ctx.stroke()}if(e.hp<e.maxHp){ctx.fillStyle='#0009';ctx.fillRect(e.x-20,e.y-size*.4,40,3);ctx.fillStyle=e.type==='boss'?'#df8a80':'#b8bd87';ctx.fillRect(e.x-20,e.y-size*.4,40*Math.max(0,e.hp/e.maxHp),3)}}
function drawAim(){if(!aim.active&&!touchAim.active)return;let a=state.aimAngle||0;ctx.save();ctx.strokeStyle=DATA.heroes[state.hero].color+'90';ctx.lineWidth=1;ctx.setLineDash([3,7]);ctx.beginPath();ctx.moveTo(state.x+Math.cos(a)*27,state.y+Math.sin(a)*27);ctx.lineTo(state.x+Math.cos(a)*95,state.y+Math.sin(a)*95);ctx.stroke();ctx.setLineDash([]);if(aim.active){let x=state.x+(aim.x-W/2),y=state.y+(aim.y-H/2);ctx.strokeStyle='#ddd4b9';ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.moveTo(x-12,y);ctx.lineTo(x-5,y);ctx.moveTo(x+5,y);ctx.lineTo(x+12,y);ctx.moveTo(x,y-12);ctx.lineTo(x,y-5);ctx.moveTo(x,y+5);ctx.lineTo(x,y+12);ctx.stroke()}ctx.restore()}
function loadHeroAnimations(){heroAnimationImage.onload=()=>{heroAnimationAtlas=transparentAtlas(heroAnimationImage);if(DATA)renderMenu()};heroAnimationImage.src='heroes-animation.png'}

function environmentSprite(c,index,x,baseY,size){if(!environmentAtlas)return;let rect=DATA.environmentRects[index],scale=size/Math.max(rect[2],rect[3]),dw=rect[2]*scale,dh=rect[3]*scale;c.drawImage(environmentAtlas,...rect,x-dw/2,baseY-dh,dw,dh)}
function loadEnvironment(){environmentImage.onload=()=>environmentAtlas=transparentAtlas(environmentImage);environmentImage.src='environment.png'}

function loadSorcerer(){sorcererImage.onload=()=>{sorcererAtlas=transparentAtlas(sorcererImage);if(DATA)renderMenu()};sorcererImage.src='sorcerer-animation.png'}
