'use strict';
// Separate preparation, release and recovery. A projectile leaves only at release.
const releaseShot=shoot,releaseSkill=activeSkill;
function shotPreparation(s){return Math.min(.28,Math.max(.07,s.cooldown*.32))}
shoot=function(){let s=state;if(s.down||s.shotWind>0||s.skillWind>0)return;if(!aim.active&&!touchAim.active&&!nearestEnemy())return;s.shotDuration=shotPreparation(s);s.shotWind=s.shotDuration;s.shotAngle=aimDirection()};
activeSkill=function(){if(mode!=='playing'||!state||state.down||netGuest()||state.skillCooldown>0||state.skillWind>0||state.wolfForm>0)return;state.skillWind=.28;state.shotWind=0;state.shotAngle=aimDirection()};
skillButton.onclick=activeSkill;
const phaseUpdate=update;
update=function(dt){let s=state;if(s.shotWind>0){s.shotWind=Math.max(0,s.shotWind-dt);if(s.shotWind===0)releaseShot()}if(s.skillWind>0){s.skillWind=Math.max(0,s.skillWind-dt);if(s.skillWind===0)releaseSkill()}phaseUpdate(dt)};
const stateFactory=newState;newState=function(){let s=stateFactory();s.combatVersion=9;return s};
const combatMigrate=migrateState;migrateState=function(s){combatMigrate(s);s.shotWind=0;s.skillWind=0;if(s.combatVersion!==9){let before=s.difficulty==='hard'?{hp:1.3,damage:1.45,speed:1.12}:s.difficulty==='easy'?{hp:.8,damage:.65,speed:.88}:{hp:1,damage:1,speed:1},now=DATA.difficulties.find(d=>d.id===s.difficulty);for(let e of s.enemies){e.hp*=now.hp/before.hp;e.maxHp*=now.hp/before.hp;e.damage*=now.damage/before.damage;e.speed*=now.speed/before.speed} s.combatVersion=9}};
// Painted limbs pivot independently at the hip. Torso stays intact; no strip warping or double images.
function limbSprite(c,image,r,x,y,width,height,clock,moving,attack=0,split=.54,hip=.68){let upper=r[3]*hip,legHeight=r[3]-upper,cut=r[2]*split,step=moving?Math.sin(clock*11):0;for(let side=0;side<2;side++){let sx=side?cut:0,sw=side?r[2]-cut:cut,pivotX=x+(sx+sw*.5)/r[2]*width,pivotY=y+height*hip;c.save();c.translate(pivotX,pivotY);c.rotate(step*(side?-.24:.24));c.translate(0,-Math.max(0,step*(side?-1:1))*height*.035);c.drawImage(image,r[0]+sx,r[1]+upper,sw,legHeight,-sw/r[2]*width*.5,-1,sw/r[2]*width,legHeight/r[3]*height+1);c.restore()}c.save();c.translate(x+width*.5,y+height*hip);c.rotate((moving?step*.015:0)-attack*.035);c.drawImage(image,r[0],r[1],r[2],upper,-width*.5,-height*hip,width,height*hip+1);c.restore()}
const heroPoseCache=new Map();
function heroPose(hero,frame,attack){let source=hero===3?sorcererAtlas:heroAnimationAtlas;if(!source)return null;let key=hero+':'+frame+':'+attack;if(heroPoseCache.has(key))return heroPoseCache.get(key);let image=document.createElement('canvas');image.width=300;image.height=300;let c=image.getContext('2d');keyframeSprite(c,hero,frame,attack,150,150,250);heroPoseCache.set(key,image);return image}
function weaponCycle(x,y,a,kind,prepare,release,enemy=false,color='#dfca9c'){let c=ctx,drawBack=prepare>0?prepare:release>0?Math.max(0,1-release/.3)*.15:0;c.save();c.translate(x,y-5);c.rotate(a);c.lineCap='round';if(kind==='bow'){let bx=20-drawBack*3;c.strokeStyle=enemy?'#c59675':'#c4a46b';c.lineWidth=2.5;c.beginPath();c.arc(bx-7,0,15,-1.05,1.05);c.stroke();c.strokeStyle='#e8d9b4';c.lineWidth=1;c.beginPath();c.moveTo(bx, -13);c.lineTo(bx-8-prepare*10,0);c.lineTo(bx,13);c.stroke();if(prepare>0){c.strokeStyle='#e9dfb8';c.lineWidth=1.5;c.beginPath();c.moveTo(bx-14-prepare*8,0);c.lineTo(bx+13-prepare*8,0);c.stroke()}}else if(kind==='staff'){c.rotate(-prepare*.18+Math.sin(release/.3*Math.PI)*.13);c.strokeStyle='#95704c';c.lineWidth=3;c.beginPath();c.moveTo(11,19);c.lineTo(22,-17);c.stroke();ellipse(c,22,-17,4,5,color)}else if(kind==='daggers'){c.rotate(-prepare*.85+Math.sin(release/.3*Math.PI)*1.3);c.strokeStyle='#e0d5e7';c.lineWidth=3;for(let side of [-1,1]){c.beginPath();c.moveTo(10,side*6);c.lineTo(26,side*6);c.stroke()}}if(kind==='staff'||kind==='violet'){let power=prepare||release/.3;c.globalAlpha=.25+power*.65;ellipse(c,24,kind==='staff'?-17:0,3+power*7,3+power*7,color);c.strokeStyle=color;c.lineWidth=1;c.beginPath();c.arc(24,kind==='staff'?-17:0,8+power*9, -state.time*4,Math.PI*1.5-state.time*4);c.stroke()} // Hands draw back during charging, then reach forward on release.
for(let side of [-1,1]){c.strokeStyle=enemy?'#a89c83':'#bea98a';c.lineWidth=2;c.beginPath();c.moveTo(3,side*8);c.lineTo(11-prepare*4,side*6);c.lineTo(21-(side<0?prepare*12:prepare*2),side*2);c.stroke()}c.restore();if(release>.2){c.save();c.globalAlpha=(release-.2)*5;c.strokeStyle=color;c.lineWidth=1.5;c.beginPath();c.arc(x+Math.cos(a)*28,y-5+Math.sin(a)*28,5+(1-release/.3)*14,0,Math.PI*2);c.stroke();c.restore()}}
drawHero=function(){let s=state,wind=s.skillWind>0?s.skillWind:s.shotWind||0,duration=s.skillWind>0?.28:s.shotDuration||.2,prep=wind>0?1-wind/duration:0,released=s.attackAnim||0,kind=weaponKind(),hasAttack=wind>0||released>0,frame=wind>0?(prep>.4?1:0):released>.18?2:released>0?3:0,useAttack=s.hero===3||s.hero===0&&kind==='bow',image=heroPose(s.hero,useAttack?frame:0,useAttack&&hasAttack);ctx.save();ctx.globalAlpha=s.down?.3:s.invuln>0&&Math.floor(s.time*15)%2?.45:1;ellipse(ctx,s.x,s.y+19,17,6,'#0007');ctx.translate(s.x,s.y);ctx.scale(Math.cos(s.aimAngle||0)<0?-1:1,1);if(image){let bob=s.moving?Math.abs(Math.sin((s.walkClock||0)*11))*1.2:0;limbSprite(ctx,image,[0,0,300,300],-44,-44-bob,88,88,s.walkClock||0,s.moving,prep,.52,.68)}else keyframeSprite(ctx,s.hero,0,false,0,0,74);ctx.restore();weaponCycle(s.x,s.y,s.aimAngle||0,kind,prep,released,false,DATA.heroes[s.hero].color)};
const fallbackEnemy=paintedFallback;
drawEnemy=function(e){if(!e.spec||!enemyDetailAtlas){if(e.type==='boss'&&spriteAtlas){let r=DATA.atlasRects[e.sprite],size=e.radius*3,w=r[2]/Math.max(r[2],r[3])*size,h=r[3]/Math.max(r[2],r[3])*size,prep=(e.shot||0)<.55?1-Math.max(0,e.shot)/.55:0;ellipse(ctx,e.x,e.y+size*.27,e.radius,e.radius*.4,'#0006');ctx.save();ctx.translate(e.x,e.y);ctx.scale(Math.cos(e.angle||0)<0?-1:1,1);if(e.hitAnim>0)ctx.globalAlpha=.6;limbSprite(ctx,spriteAtlas,r,-w/2,-h/2,w,h,e.walkClock||0,e.attackWind<=0,prep,.5,.72);ctx.restore();weaponCycle(e.x,e.y,e.angle||0,'staff',prep,e.attackAnim||0,true,'#e78d7f');if(e.hp<e.maxHp){ctx.fillStyle='#0009';ctx.fillRect(e.x-30,e.y-h/2-5,60,4);ctx.fillStyle='#df8a80';ctx.fillRect(e.x-30,e.y-h/2-5,60*e.hp/e.maxHp,4)}return}fallbackEnemy(e);return}let r=enemyDetailRects[e.theme*4+(e.atlasForm??e.form)],size=e.type==='mini'?108:78,width=r[2]/r[3]*size,clock=e.walkClock||0,moving=(e.castWind||0)<=0&&(e.attackWind||0)<=0&&!(e.ranged&&Math.hypot(state.x-e.x,state.y-e.y)<340&&Math.hypot(state.x-e.x,state.y-e.y)>180),prep=e.castWind>0?1-e.castWind/.65:e.attackWind>0?1-e.attackWind/.38:0;ellipse(ctx,e.x,e.y+18,e.radius||18,6,'#0006');ctx.save();ctx.translate(e.x,e.y);ctx.scale(Math.cos(e.angle||0)<0?-1:1,1);if(e.hitAnim>0)ctx.globalAlpha=.55;limbSprite(ctx,enemyDetailAtlas,r,-width/2,-size+22,width,size,clock,moving,prep,.52,.7);ctx.restore();let angle=e.castWind>0?e.castAngle:e.angle||0,color=SHOT_COLORS[e.shotKind]||THEMES[e.theme].trap;weaponCycle(e.x,e.y,angle,e.weaponKind||(e.ranged?'staff':'daggers'),prep,e.attackAnim||0,true,color);if(e.castWind>0){ctx.save();ctx.strokeStyle=color;ctx.globalAlpha=.3+prep*.5;ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.lineTo(e.x+Math.cos(angle)*125,e.y+Math.sin(angle)*125);ctx.stroke();ctx.restore()}if(e.hp<e.maxHp){ctx.fillStyle='#000a';ctx.fillRect(e.x-20,e.y-size+14,40,3);ctx.fillStyle=color;ctx.fillRect(e.x-20,e.y-size+14,40*Math.max(0,e.hp/e.maxHp),3)}};
