'use strict';
// Expansion uses local Canvas geometry and Web Audio: no external asset services.
const RARITIES=[{id:'common',name:'Обычная',color:'#bcc9b0',factor:1,weight:55},{id:'rare',name:'Редкая',color:'#7fb9ef',factor:1.35,weight:28},{id:'epic',name:'Эпическая',color:'#c89af3',factor:1.75,weight:13},{id:'legendary',name:'Легендарная',color:'#efc66c',factor:2.25,weight:4}];
function rollRarity(){let r=Math.random()*100;return RARITIES.find(a=>(r-=a.weight)<0)||RARITIES[0]}
function rarityDescription(u){let f=u.rarity.factor;switch(u.id){case'power':return `Урон +${Math.round(25*f)}%.`;case'haste':return `Интервал атак −${Math.round(15*f)}%.`;case'speed':return `Скорость +${Math.round(12*f)}%.`;case'health':return `Максимум HP +${Math.round(25*f)}, лечение ${Math.round(35*f)}.`;case'multi':return 'Дополнительный снаряд (до 6).'+(f>1?' Урон +'+Math.round((f-1)*8)+'%.':'');default:return u.description+(f>1?` Дополнительно: ${u.weapon?'урон +'+Math.round((f-1)*18)+'%':'защита +'+Math.round((f-1)*8)+' п.п.'}.`:'')}}
const originalChoose=choose;
offer=function(){if(!state.pending){mode='playing';closeDialog();return}mode='upgrade';let pool=DATA.upgrades.filter(u=>!(u.id==='multi'&&state.multi>=6)&&!(u.id==='plate'&&state.armorReduction>=.3)&&!(u.id==='cloak'&&state.cloakBonus)&&!(u.weapon&&state.weapon===u.name));choices=[];while(choices.length<3&&pool.length){let i=Math.floor(Math.random()*pool.length),u=pool.splice(i,1)[0];choices.push({...u,rarity:rollRarity()})}dialog(`<div class="eyebrow">НОВАЯ СИЛА · УРОВЕНЬ ${state.level}</div><h2>Выбери свой путь</h2><p>Редкость усиливает эффект. Выбери одно улучшение.</p><div class="upgradeGrid">${choices.map((u,i)=>`<button class="upgrade" style="border-color:${u.rarity.color}" data-up="${i}"><span style="color:${u.rarity.color}">${u.icon}</span><small style="color:${u.rarity.color}">${u.rarity.name} · ${u.type}</small><b>${u.name}</b><p>${rarityDescription(u)}</p></button>`).join('')}</div>`);document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>choose(choices[+b.dataset.up]))};
choose=function(u){let s=state,f=u.rarity?.factor||1;if(u.id==='power')s.damage*=(1+.25*f)/1.25;if(u.id==='haste')s.cooldown=Math.max(.12,s.cooldown*(1-.15*f)/.85);if(u.id==='speed')s.speed*=(1+.12*f)/1.12;if(u.id==='health'){s.maxHp+=Math.round(25*f)-25;s.hp=Math.min(s.maxHp,s.hp+Math.round(35*f)-35)}if(u.id==='multi')s.damage*=1+(f-1)*.08;if(u.weapon)s.damage*=1+(f-1)*.18;let armor=u.armor;originalChoose(u);if(armor){s.armorReduction=Math.min(.6,s.armorReduction+(f-1)*.08);saveRun()}};
const originalSpawn=spawn;
spawn=function(type){if(type==='boss'){originalSpawn(type);let b=state.enemies.at(-1);if(b?.type==='boss'){b.rage=5;b.theme=state.stage%5}return}let roster=DATA.enemyRosters[state.stage%5].filter(e=>e.type===['normal','rare','mini'][type]),spec=roster[Math.floor(Math.random()*roster.length)],old=DATA.enemies[type];DATA.enemies[type]=spec;let before=state.enemies.length;originalSpawn(type);DATA.enemies[type]=old;if(state.enemies.length>before){let e=state.enemies.at(-1);e.spec=true;e.rangedTimer=2+Math.random()*2}};
const oldMigrate=migrateState;migrateState=function(s){oldMigrate(s);s.skillCooldown=s.skillCooldown||0;s.skillEffects=[]};
function activeSkill(){if(mode!=='playing'||!state||state.down||netGuest())return;let s=state,h=DATA.heroes[s.hero];if((s.skillCooldown||0)>0)return;s.skillCooldown=h.active.cooldown;s.attackAnim=.3;let a=aimDirection();s.skillEffects??=[];s.skillEffects.push({x:s.x,y:s.y,life:.65,color:h.color,radius:s.hero===1?240:95});if(s.hero===0){for(let i=-4;i<=4;i++)s.projectiles.push({x:s.x,y:s.y,vx:Math.cos(a+i*.11)*690,vy:Math.sin(a+i*.11)*690,life:2.5,damage:s.damage*2.8,pierce:7,splash:0,hit:[],kind:'bow',color:h.color})}else if(s.hero===1){for(let e of s.enemies)if(Math.hypot(e.x-s.x,e.y-s.y)<240){e.hp-=s.damage*9;e.hitAnim=.3}particles(s.x,s.y,h.color,35)}else if(s.hero===2){s.invuln=1.5;moveActor(s,Math.cos(a)*220,Math.sin(a)*220);for(let e of s.enemies)if(Math.hypot(e.x-s.x,e.y-s.y)<110){e.hp-=s.damage*7;e.hitAnim=.3}particles(s.x,s.y,h.color,25)}else{for(let i=-1;i<=1;i++)s.projectiles.push({x:s.x,y:s.y,vx:Math.cos(a+i*.1)*420,vy:Math.sin(a+i*.1)*420,life:3,damage:s.damage*8,pierce:15,splash:120,hit:[],kind:'violet',color:h.color})}weaponSound(s.hero===3?'violet':'staff');hud()}
window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&mode==='playing'){e.preventDefault();activeSkill()}});
const skillButton=document.createElement('button');skillButton.id='activeSkill';skillButton.className='skillButton';skillButton.onclick=activeSkill;$('game').append(skillButton);
const originalHud=hud;hud=function(){originalHud();let cd=Math.max(0,state.skillCooldown||0),h=DATA.heroes[state.hero];skillButton.disabled=cd>0||state.down||netGuest();skillButton.textContent=h.active.name+(cd>0?' · '+Math.ceil(cd)+' с':' · ПРОБЕЛ');skillButton.title=h.active.description};
const originalUpdate=update;update=function(dt){let s=state;s.skillCooldown=Math.max(0,(s.skillCooldown||0)-dt);s.skillEffects=(s.skillEffects||[]).filter(e=>(e.life-=dt)>0);for(let e of s.enemies){if(e.hp<=0)continue;if(e.ranged){e.rangedTimer-=dt;if(e.rangedTimer<=0){let a=Math.atan2(s.y-e.y,s.x-e.x);s.projectiles.push({x:e.x,y:e.y,vx:Math.cos(a)*210,vy:Math.sin(a)*210,life:4,hostile:true,damage:e.damage*.7});e.attackAnim=.3;e.rangedTimer=3.4}}if(e.type==='boss'){e.rage=(e.rage||5)-dt;if(e.rage<=0){let n=e.hp<e.maxHp*.5?14:9;for(let i=0;i<n;i++){let a=i*Math.PI*2/n+s.time*.2;s.projectiles.push({x:e.x,y:e.y,vx:Math.cos(a)*190,vy:Math.sin(a)*190,life:5,hostile:true,damage:e.damage*.8})}e.rage=e.hp<e.maxHp*.5?3.8:6;e.attackAnim=.3}}}originalUpdate(dt)};
const originalDraw=draw;draw=function(){originalDraw();if(!state)return;ctx.save();ctx.translate(W/2-state.x,H/2-state.y);for(let e of state.skillEffects||[]){ctx.globalAlpha=e.life/.65;ctx.strokeStyle=e.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,e.radius*(1-e.life/.75),0,Math.PI*2);ctx.stroke()}ctx.restore()};
const oldEnemyDraw=drawEnemy;
drawEnemy=function(e){if(!e.spec){oldEnemyDraw(e);return}let c=ctx,t=THEMES[e.theme],walk=Math.sin((e.walkClock||0)*12),big=e.form===3,body=big?22:e.form===1?15:11,bob=Math.abs(walk)*2;c.save();ellipse(c,e.x,e.y+15,body+4,6,'#0006');c.translate(e.x,e.y-bob);c.scale(Math.cos(e.angle)<0?-1:1,1);if(e.hitAnim>0)c.globalAlpha=.5;c.strokeStyle=t.edge;c.lineWidth=big?7:4;c.lineCap='round';for(let side of [-1,1]){c.beginPath();c.moveTo(side*body*.5,9);c.lineTo(side*body*.6+walk*side*5,22);c.stroke();c.beginPath();c.moveTo(side*body*.7,-4);c.lineTo(side*(body+6),7+walk*side*5);c.stroke()}ellipse(c,0,0,body,body*1.12,e.form===2?t.trap:t.stone);c.strokeStyle=t.edge;c.lineWidth=2;c.strokeRect(-body*.65,-9,body*1.3,19);ellipse(c,0,-body-4,body*.6,body*.65,t.edge);c.fillStyle='#f4dec0';c.fillRect(-5,-body-6,3,3);c.fillRect(3,-body-6,3,3);if(e.form===2){c.fillStyle=t.trap;c.beginPath();c.moveTo(-13,-body-6);c.lineTo(0,-body-29);c.lineTo(13,-body-6);c.fill()}if(e.theme===0){c.strokeStyle='#9a8661';c.beginPath();c.moveTo(-6,-body-10);c.lineTo(-12,-body-21);c.moveTo(6,-body-10);c.lineTo(12,-body-21);c.stroke()}else if(e.theme===1){ellipse(c,0,8,body+3,5,'#a9c56a55');for(let i=0;i<3;i++)ellipse(c,-body+i*body,0,3,3,'#c8d68b')}else if(e.theme===2){c.fillStyle='#bee9f4';c.beginPath();c.moveTo(-body,0);c.lineTo(-body-7,-15);c.lineTo(-body+7,-5);c.fill()}else if(e.theme===3){c.fillStyle='#fcaf63';c.beginPath();c.moveTo(-7,-body-9);c.lineTo(0,-body-24-Math.sin(state.time*12)*4);c.lineTo(7,-body-9);c.fill()}else{c.globalAlpha*=.7;c.fillStyle='#9670b6';for(let side of [-1,1]){c.beginPath();c.moveTo(side*8,-6);c.lineTo(side*(body+19),-17+walk*7);c.lineTo(side*(body+10),12);c.fill()}}c.restore();drawWeapon(e.x,e.y,e.angle,e.ranged?'staff':e.form===0?'bow':'daggers',e.attackAnim||0,true);if(e.attackWind>0){c.strokeStyle='#e4bc7b';c.beginPath();c.arc(e.x,e.y,e.radius+8,0,Math.PI*2);c.stroke()}if(e.hp<e.maxHp){c.fillStyle='#000a';c.fillRect(e.x-20,e.y-35,40,3);c.fillStyle=t.trap;c.fillRect(e.x-20,e.y-35,40*Math.max(0,e.hp/e.maxHp),3)}};
// Additional seeded, non-colliding scenery: ruins, flowers, bones and magical mosaics.
const oldDecoration=drawDecoration;drawDecoration=function(x,y,v,theme){oldDecoration(x,y,v,theme);let c=ctx,t=THEMES[theme];c.save();c.translate(x,y);if(v<.22){c.strokeStyle=t.edge+'60';c.lineWidth=1;for(let i=0;i<4;i++){let a=i*1.8;c.beginPath();c.moveTo(0,0);c.lineTo(Math.cos(a)*12,Math.sin(a)*7);c.stroke()}ellipse(c,0,0,3,2,theme===0?'#c6afcf':theme===1?'#b8c263':t.trap)}else if(v<.38){c.fillStyle=t.stone+'80';c.fillRect(-12,-4,24,8);c.strokeStyle=t.edge+'50';c.strokeRect(-10,-4,10,7);c.strokeRect(2,-4,8,7)}else if(v<.48){c.strokeStyle=theme<2?'#c6c1a380':t.trap+'50';c.beginPath();c.ellipse(0,0,13,8,0,0,Math.PI*2);c.moveTo(-9,0);c.lineTo(9,0);c.moveTo(0,-6);c.lineTo(0,6);c.stroke()}c.restore()};
function audioContext(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();return audio}catch{return null}}
function tone(freq,dur,gain,type='sine',delay=0,end=freq){let a=audioContext();if(!a||!gain)return;let now=a.currentTime+delay,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),now+dur);g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(gain,now+.012);g.gain.exponentialRampToValueAtTime(.001,now+dur);o.connect(g);g.connect(a.destination);o.start(now);o.stop(now+dur+.02)}
function weaponSound(kind){let v=prefs.volume*.09;if(kind==='bow'){tone(1100,.075,v,'triangle',0,220)}else if(kind==='daggers'){tone(1750,.04,v*.6,'sawtooth',0,600);tone(950,.05,v*.4,'triangle',.045,250)}else if(kind==='violet'){tone(90,.24,v,'sine',0,360);tone(420,.18,v*.5,'triangle',.03,85)}else{tone(180,.15,v,'sawtooth',0,55);tone(680,.12,v*.4,'sine',.02,160)}}
let musicTimer=null,musicStep=0;function startMusic(){if(musicTimer)return;audioContext();let notes=[220,261.63,293.66,329.63,392,329.63,293.66,261.63,196,246.94,293.66,349.23,392,349.23,293.66,246.94];function tick(){if(audio?.state==='running'&&!document.hidden&&(prefs.musicVolume??.18)>0){let v=(prefs.musicVolume??.18)*.045,n=notes[musicStep%notes.length],shift=state?Math.pow(2,(state.stage%5-2)/12):1;tone(n*shift,1.35,v,'sine');if(musicStep%4===0){tone(n*.5*shift,2.7,v*.7,'triangle');tone(n*1.5*shift,2.1,v*.35,'sine',.12)}musicStep++}musicTimer=setTimeout(tick,450)}tick()}
window.addEventListener('pointerdown',()=>startMusic(),{once:true});
