'use strict';
const cloneState=value=>JSON.parse(JSON.stringify(value));
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
let DATA,selected=0,slot=0,state=null,mode='menu',W=innerWidth,H=innerHeight,last=0,keys={},stick={x:0,y:0},choices=[],saveTimer=0,toastTimer=0,audio=null,atlas=new Image(),spriteAtlas=null;
let aim={x:0,y:0,active:false},touchAim={angle:0,active:false};
let prefs={volume:.25,particles:true,shake:true,difficulty:'medium'},records={best:0},saves=[null,null,null];
try{prefs={...prefs,...JSON.parse(localStorage.getItem('vb-settings')||'{}')};records={...records,...JSON.parse(localStorage.getItem('vb-record')||'{}')};saves=JSON.parse(localStorage.getItem('vb-saves')||'[null,null,null]');if(!Array.isArray(saves)||saves.length!==3)saves=[null,null,null]}catch{}
function persist(){try{localStorage.setItem('vb-settings',JSON.stringify(prefs));localStorage.setItem('vb-record',JSON.stringify(records));localStorage.setItem('vb-saves',JSON.stringify(saves))}catch{toast('Браузер не разрешил сохранить прогресс')}}
function sound(freq=500,duration=.06){if(!prefs.volume)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(prefs.volume*.13,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function sprite(c,index,x,y,size){if(atlas.complete&&atlas.naturalWidth){let rect=DATA&&DATA.atlasRects?DATA.atlasRects[index]:[(index%4)*atlas.width/4,Math.floor(index/4)*atlas.height/4,atlas.width/4,atlas.height/4];let scale=size/Math.max(rect[2],rect[3]),dw=rect[2]*scale,dh=rect[3]*scale;c.drawImage(spriteAtlas||atlas,...rect,x-dw/2,y-dh/2,dw,dh)}else{c.fillStyle=index<3?['#a5d590','#8ab5ef','#c99cde'][index]:'#c09b8f';c.beginPath();c.arc(x,y,size*.25,0,Math.PI*2);c.fill()}}
function difficulty(){return DATA.difficulties.find(d=>d.id===(state?state.difficulty:prefs.difficulty))||DATA.difficulties[1]}
function renderMenu(){ $('difficulty').value=prefs.difficulty;$('difficultyHint').textContent=difficulty().description; $('record').innerHTML=records.best.toLocaleString('ru')+' <em>очков</em>'; $('heroCards').innerHTML=DATA.heroes.map((h,i)=>`<button class="hero ${selected===i?'selected':''}" data-hero="${i}" aria-pressed="${selected===i}"><span class="chosen">✓</span><div class="heroArt"><canvas id="portrait${i}" width="300" height="320"></canvas></div><div class="heroInfo"><small>${h.class}</small><h3>${h.name}</h3><div class="tag">${h.tag}</div><p>${h.description}</p><div class="stats"><span>♡ ${h.hp}</span><span>⚔ ${h.damage}</span><span>➶ ${h.speed}</span></div></div></button>`).join('');document.querySelectorAll('[data-hero]').forEach(b=>b.onclick=()=>{selected=+b.dataset.hero;renderMenu();sound(420)});DATA.heroes.forEach((h,i)=>{let c=$('portrait'+i).getContext('2d');c.imageSmoothingEnabled=false;animatedHeroSprite(c,i,0,false,150,163,300)});$('worlds').innerHTML=DATA.locations.map((l,i)=>`<div class="world" style="background:${l.color}"><b>0${i+1}</b>${l.name}</div>`).join('');$('slotHint').textContent='Слот '+(slot+1)}
function newState(){let h=DATA.heroes[selected];return {version:3,difficulty:prefs.difficulty,walkClock:0,moving:false,aimAngle:0,attackAnim:0,attackCount:0,hero:selected,score:0,time:0,level:1,xp:0,nextXp:DATA.progression.initialXp,stage:0,x:0,y:0,hp:h.hp,maxHp:h.hp,speed:h.speed,damage:h.damage,cooldown:h.cooldown,pierce:h.pierce||1,splash:h.splash||0,crit:h.crit||0,multi:1,armorReduction:0,weapon:h.weapon,armor:h.armor,attackTimer:0,spawnTimer:0,hits:0,invuln:0,enemies:[],projectiles:[],loot:[],particles:[],bossSpawned:false,bossDefeated:false,bossTimer:0,upgrades:{},kills:0,pending:0,cloakBonus:false}}
function begin(saved=false){sound(330,.15);state=saved?cloneState(saves[slot].state):newState();if(saved){selected=state.hero;migrateState(state)}resetWorld();mode='playing';$('menu').classList.add('hidden');$('game').classList.remove('hidden');closeDialog();saveTimer=0;keys={};stick={x:0,y:0};aim.active=false;touchAim.active=false;resize();toast(DATA.locations[state.stage%5].name+' · '+difficulty().name);saveRun();hud()}
function xpForLevel(level){let v=DATA.progression.initialXp;for(let i=1;i<level;i++)v=Math.round(v*DATA.progression.growth+DATA.progression.increment);return v}
function migrateState(s){s.difficulty=s.difficulty||'medium';s.walkClock=s.walkClock||0;s.attackAnim=0;s.aimAngle=s.aimAngle||0;s.moving=false;if(s.version!==3){let ratio=s.xp/s.nextXp;s.nextXp=xpForLevel(s.level);s.xp=Math.floor(ratio*s.nextXp);s.version=3}for(let e of s.enemies){e.walkClock=e.walkClock||0;e.attackCooldown=e.attackCooldown||0;e.attackWind=0;e.attackAnim=0;e.hitAnim=0}if(isBlocked(s.x,s.y)){for(let r=20;r<300;r+=20){let placed=false;for(let i=0;i<16;i++){let a=i*Math.PI/8,nx=s.x+Math.cos(a)*r,ny=s.y+Math.sin(a)*r;if(!isBlocked(nx,ny)){s.x=nx;s.y=ny;placed=true;break}}if(placed)break}}}
function saveRun(){if(!state)return;if(netActive()){records.coopBest=Math.max(records.coopBest||0,state.score);persist();return;}saves[slot]={date:new Date().toISOString(),state:cloneState(state)};records.best=Math.max(records.best,state.score);persist()}
function dialog(html){$('dialog').innerHTML=html;$('overlay').classList.remove('hidden')}
function closeDialog(){$('overlay').classList.add('hidden')}
function menu(){if(state&&mode!=='dead')saveRun();if(netActive())leaveCoop();mode='menu';state=null;closeDialog();$('game').classList.add('hidden');$('menu').classList.remove('hidden');renderMenu()}
function clearMovement(){keys={};stick={x:0,y:0};touchAim.active=false;$('joystick').firstElementChild.style.transform='';$('aimJoystick').firstElementChild.style.transform='';if(state)state.moving=false}
function pause(){if(mode!=='playing')return;clearMovement();mode='paused';saveRun();dialog(`<div class="eyebrow">СТРАНСТВИЕ ПРИОСТАНОВЛЕНО</div><h2>Тихий привал</h2><p>Уровень ${state.level} · ${state.score.toLocaleString('ru')} очков<br>Сложность: ${difficulty().name}. ${netActive()?(netHost()?'Общая пауза для всего отряда.':'Локальная пауза: союзники продолжают бой.'):'Прогресс сохранён в слоте '+(slot+1)+'.'}</p><button class="primary" id="resume">Продолжить →</button><button class="secondary" id="pauseSettings">Настройки</button><button class="secondary" id="exit">${netActive()?'Выйти из лобби':'Сохранить и выйти'}</button>`);$('resume').onclick=()=>{mode='playing';closeDialog()};$('exit').onclick=menu;$('pauseSettings').onclick=()=>settings(true)}
function settings(inGame=false){dialog(`<div class="eyebrow">ПОДСТРОЙ МИР ПОД СЕБЯ</div><h2>Настройки</h2><label>Громкость эффектов <input id="volume" type="range" min="0" max="1" step=".05" value="${prefs.volume}" aria-label="Громкость"></label><label>Частицы <input id="particles" type="checkbox" ${prefs.particles?'checked':''}></label><label>Встряска при уроне <input id="shake" type="checkbox" ${prefs.shake?'checked':''}></label><p>Движение: WASD / стрелки / джойстик.<br>Атаки автоматические в сторону мыши. На телефоне — правый джойстик.<br>Без ручного прицела герой выбирает ближайшую цель. ESC или P — пауза.<br>Опыт подбирается при приближении. Зелье лечит 30 HP.<br>Препятствия блокируют движение и снаряды. Опасные зоны наносят урон; знак ! предупреждает о срабатывании.</p><button class="primary" id="doneSettings">Готово</button>`);$('volume').oninput=e=>{prefs.volume=+e.target.value;sound()};$('particles').onchange=e=>prefs.particles=e.target.checked;$('shake').onchange=e=>prefs.shake=e.target.checked;$('doneSettings').onclick=()=>{persist();if(inGame){mode='playing';pause()}else closeDialog()}}
function saveMenu(){dialog(`<div class="eyebrow">ПРОГРЕСС ХРАНИТСЯ В ЭТОМ БРАУЗЕРЕ</div><h2>Твои странствия</h2>${saves.map((save,i)=>`<div class="slot"><div><b>Слот ${i+1}${slot===i?' · выбран':''}</b><small>${save?`${DATA.heroes[save.state.hero].name} · ур. ${save.state.level} · ${save.state.score.toLocaleString('ru')} очков · ${(DATA.difficulties.find(d=>d.id===save.state.difficulty)||DATA.difficulties[1]).name}`:'Пустое сохранение'}</small></div><div class="slotActions"><button class="quiet" data-slot="${i}">${save?'Продолжить':'Выбрать'}</button>${save?`<button class="deleteSave" data-delete="${i}" aria-label="Удалить сохранение из слота ${i+1}">Удалить</button>`:''}</div></div>`).join('')}<p>«Начать странствие» начинает новую игру в выбранном слоте. Кооператив не заменяет одиночные сохранения.</p><button class="secondary" id="back">Назад</button>`);document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{slot=+b.dataset.slot;if(saves[slot])begin(true);else{closeDialog();renderMenu()}});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteSave(+b.dataset.delete));$('back').onclick=closeDialog}
function deleteSave(i){if(!saves[i])return;dialog(`<h2>Удалить сохранение?</h2><p>Будет очищен слот ${i+1}. Остальные сохранения и рекорд останутся.</p><button class="primary" id="confirmDelete">Удалить слот ${i+1}</button><button class="secondary" id="cancelDelete">Отмена</button>`);$('confirmDelete').onclick=()=>{saves[i]=null;persist();saveMenu();renderMenu()};$('cancelDelete').onclick=saveMenu}
function offer(){if(!state.pending){mode='playing';closeDialog();return}mode='upgrade';choices=[...DATA.upgrades].filter(u=>!(u.id==='multi'&&state.multi>=6)&&!(u.id==='plate'&&state.armorReduction===.3)&&!(u.id==='cloak'&&state.cloakBonus)&&!((u.weapon)&&state.weapon===u.name)).sort(()=>Math.random()-.5).slice(0,3);dialog(`<div class="eyebrow">НОВАЯ СИЛА · УРОВЕНЬ ${state.level}</div><h2>Выбери свой путь</h2><p>Одно улучшение. Три возможности.</p><div class="upgradeGrid">${choices.map((u,i)=>`<button class="upgrade" data-up="${i}"><span>${u.icon}</span><small>${u.type.toUpperCase()}</small><b>${u.name}</b><p>${u.description}</p></button>`).join('')}</div>`);document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>choose(choices[+b.dataset.up]))}
function choose(u){let s=state;s.upgrades[u.id]=(s.upgrades[u.id]||0)+1;switch(u.id){case'power':s.damage*=1.25;break;case'haste':s.cooldown=Math.max(.12,s.cooldown*.85);break;case'speed':s.speed*=1.12;break;case'health':s.maxHp+=25;s.hp=Math.min(s.maxHp,s.hp+35);break;case'multi':s.multi++;break;case'bow':s.weapon=u.name;s.pierce=4;s.splash=0;s.crit=0;s.damage*=1.2;break;case'staff':s.weapon=u.name;s.splash=100;s.pierce=1;s.crit=0;s.damage*=1.2;break;case'daggers':s.weapon=u.name;s.pierce=1;s.splash=0;s.crit=4;s.cooldown=Math.max(.12,s.cooldown*.75);break;case'violet':s.weapon=u.name;s.pierce=2;s.splash=60;s.crit=0;s.damage*=1.2;break;case'plate':s.armor=u.name;s.armorReduction=.3;if(s.cloakBonus){s.speed/=1.1;s.cloakBonus=false}break;case'cloak':s.armor=u.name;s.armorReduction=.15;if(!s.cloakBonus){s.speed*=1.1;s.cloakBonus=true}break;}s.pending--;sound(780,.15);saveRun();offer()}
function gainXP(v){state.xp+=v;while(state.xp>=state.nextXp){state.xp-=state.nextXp;state.level++;state.nextXp=Math.round(state.nextXp*DATA.progression.growth+DATA.progression.increment);state.pending++}}
function stageFor(score){return Math.floor(score/DATA.locationStep)}
function transition(){let s=state,next=Math.min(stageFor(s.score),s.stage+1);if(next===s.stage||!s.bossDefeated)return;s.stage=next;resetWorld();s.enemies=[];s.projectiles=[];s.loot=[];s.x=0;s.y=0;s.bossSpawned=false;s.bossDefeated=false;s.bossTimer=0;s.spawnTimer=0;s.invuln=2;if(netHost()){for(let a of Object.values(s.allies||{})){a.x=35;a.y=35;a.targetX=35;a.targetY=35;a.invuln=2}}toast(DATA.locations[s.stage%5].name+' · Круг '+(Math.floor(s.stage/5)+1));saveRun()}
function spawn(type){let s=state,ang=Math.random()*Math.PI*2,dist=Math.max(W,H)*.65+70,scale=(1+s.stage*.3+s.time/700)*(netHost()?1+Math.max(0,net.members.length-1)*.35:1);let base=type==='boss'?{name:DATA.locations[s.stage%5].boss,sprite:DATA.locations[s.stage%5].sprite,hp:2200,speed:50,damage:30,score:1000,xp:400,type:'boss'}:DATA.enemies[type];let e={...base,x:s.x+Math.cos(ang)*dist,y:s.y+Math.sin(ang)*dist,hp:base.hp*scale*difficulty().hp,maxHp:base.hp*scale*difficulty().hp,damage:base.damage*difficulty().damage,speed:base.speed*(1+Math.min(s.stage*.035,.5))*difficulty().speed,radius:base.type==='boss'?46:base.type==='mini'?26:15,phase:Math.random()*6,shot:3,walkClock:0,attackWind:0,attackCooldown:0,attackAnim:0,hitAnim:0,angle:0,id:++s.hits};for(let i=0;i<12&&isBlocked(e.x,e.y,e.radius*.65);i++){e.x+=Math.cos(ang+i)*40;e.y+=Math.sin(ang+i)*40}if(!isBlocked(e.x,e.y,e.radius*.65))s.enemies.push(e)}
function nearestEnemy(){let best=null,dist=Infinity;for(let e of state.enemies){if(e.hp<=0)continue;let d=(e.x-state.x)**2+(e.y-state.y)**2;if(d<dist){dist=d;best=e}}return best}
function aimDirection(){if(touchAim.active)return touchAim.angle;if(aim.active)return Math.atan2(aim.y-H/2,aim.x-W/2);let target=nearestEnemy();return target?Math.atan2(target.y-state.y,target.x-state.x):(state.aimAngle||0)}
function shoot(){let s=state;if(s.down)return;if(!aim.active&&!touchAim.active&&!nearestEnemy())return;let ang=aimDirection();s.aimAngle=ang;s.attackAnim=.3;s.hits++;s.attackCount=(s.attackCount||0)+1;let kind=weaponKind(),eventSeq=netShot(ang),bullets=netGuest()?netPredicted:s.projectiles;for(let i=0;i<s.multi;i++){let a=ang+(i-(s.multi-1)/2)*.12;bullets.push({x:s.x+Math.cos(a)*22,y:s.y+Math.sin(a)*22,vx:Math.cos(a)*550,vy:Math.sin(a)*550,life:2.2,damage:s.damage*(s.crit&&s.attackCount%s.crit===0?2:1),pierce:s.pierce,splash:s.splash,hit:[],hostile:false,kind,color:DATA.heroes[s.hero].color,owner:net?.playerId,eventSeq})}sound(s.splash?220:550,.035)}
function particles(x,y,color,n=6){if(!prefs.particles)return;for(let i=0;i<n;i++){let a=Math.random()*6.28;state.particles.push({x,y,vx:Math.cos(a)*90,vy:Math.sin(a)*90,life:.5,color})}if(state.particles.length>350)state.particles.splice(0,state.particles.length-350)}
function hurt(v){let s=state;if(s.invuln>0)return;s.hp-=v*(1-s.armorReduction);s.invuln=.7;particles(s.x,s.y,'#ef8f89',12);sound(95,.13);if(s.hp<=0)die()}
function die(){state.hp=0;if(netActive()&&Object.values(state.allies||{}).some(a=>a.hp>0&&!a.down)){state.down=true;toast('Ты выбыл. Союзники продолжают бой!');return}if(netActive())state.down=true;let recordKey=netActive()?'coopBest':'best';records[recordKey]=Math.max(records[recordKey]||0,state.score);if(!netActive())saves[slot]=null;persist();mode='dead';dialog(`<div class="eyebrow">ТВОЯ ИСТОРИЯ ОСТАНЕТСЯ</div><h2>Сумерки настигли тебя</h2><p>${DATA.heroes[state.hero].name} · Уровень ${state.level}<br>${Math.floor(state.time/60)} мин ${Math.floor(state.time%60)} сек · ${state.kills} поверженных врагов</p><div class="record"><span>✧</span><strong>${state.score.toLocaleString('ru')} <em>очков</em></strong></div><p>${netActive()?'Рекорд отряда':'Личный рекорд'}: ${(netActive()?(records.coopBest||0):records.best).toLocaleString('ru')}</p><button class="primary" id="retry">Попробовать ещё раз ↗</button><button class="secondary" id="deadMenu">Главное меню</button>`);$('retry').onclick=()=>{if(netActive())leaveCoop();begin()};$('deadMenu').onclick=menu}
function update(dt){let s=state;updateAllies(dt);if(netHost()&&!netParty().length){die();return}s.time+=dt;s.bossTimer+=dt;s.invuln=Math.max(0,s.invuln-dt);s.attackAnim=Math.max(0,(s.attackAnim||0)-dt);s.aimAngle=aimDirection();let mx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0)+stick.x,my=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0)+stick.y,len=Math.hypot(mx,my);if(len>1){mx/=len;my/=len}if(s.down){mx=0;my=0}let moved=moveActor(s,mx*s.speed*dt,my*s.speed*dt);s.moving=moved>.01;if(s.moving)s.walkClock+=moved/s.speed;if(!s.down)checkTraps();if(mode==='dead')return;s.attackTimer-=dt;if(s.attackTimer<=0){shoot();s.attackTimer=s.cooldown}s.spawnTimer-=dt;if(s.spawnTimer<=0&&s.enemies.length<180){let r=Math.random();spawn(r<.03?2:r<.19?1:0);s.spawnTimer=Math.max(.13,(.85-s.time*.001-s.stage*.035)*difficulty().spawn/(netHost()?1+Math.max(0,net.members.length-1)*.25:1))}if(!s.bossSpawned&&(s.score-s.stage*5000>=3200||s.bossTimer>=150)){spawn('boss');s.bossSpawned=true;toast(DATA.locations[s.stage%5].boss+' приближается!')}
for(let e of s.enemies){if(e.hp<=0)continue;let target=netHost()?closestParty(e.x,e.y):s;if(!target)continue;let dx=target.x-e.x,dy=target.y-e.y,d=Math.hypot(dx,dy)||1;e.angle=Math.atan2(dy,dx);e.attackAnim=Math.max(0,(e.attackAnim||0)-dt);e.hitAnim=Math.max(0,(e.hitAnim||0)-dt);e.attackCooldown=Math.max(0,(e.attackCooldown||0)-dt);if(e.attackWind>0){e.attackWind-=dt;if(e.attackWind<=0){e.attackAnim=.3;e.attackCooldown=.85;if(d<e.radius+29){if(netHost())hurtParty(target,e.damage);else hurt(e.damage);if(mode==='dead')return}}}else{let moved=steerEnemy(e,dx,dy,dt);e.walkClock=(e.walkClock||0)+moved/e.speed;if(d<e.radius+22&&e.attackCooldown<=0)e.attackWind=.38}if(e.type==='boss'){e.shot-=dt;if(e.shot<=0){let a=Math.atan2(dy,dx);e.attackAnim=.3;for(let j=-1;j<=1;j++)s.projectiles.push({x:e.x,y:e.y,vx:Math.cos(a+j*.25)*170,vy:Math.sin(a+j*.25)*170,life:5,hostile:true,damage:e.damage*.7});e.shot=2.5}}}
for(let p of s.projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(isBlocked(p.x,p.y,4)){p.life=0;particles(p.x,p.y,'#d5c5a0',2);continue}if(p.hostile){let target=netHost()?closestParty(p.x,p.y):s;if(target&&Math.hypot(p.x-target.x,p.y-target.y)<20){if(netHost())hurtParty(target,p.damage);else hurt(p.damage);p.life=0;if(mode==='dead')return}continue}for(let e of s.enemies){if(e.hp<=0||p.life<=0||p.hit.includes(e.id))continue;if(Math.hypot(p.x-e.x,p.y-e.y)<e.radius+8){p.hit.push(e.id);e.hp-=p.damage;e.hitAnim=.16;particles(e.x,e.y,p.color||DATA.heroes[s.hero].color,4);if(p.splash){for(let other of s.enemies){if(other!==e&&Math.hypot(other.x-e.x,other.y-e.y)<p.splash){other.hp-=p.damage*.65;other.hitAnim=.16}}particles(e.x,e.y,p.kind==='violet'?'#bb8aed':'#e9b06e',18)}p.pierce--;if(p.pierce<=0)p.life=0}}}
s.projectiles=s.projectiles.filter(p=>p.life>0);for(let e of s.enemies){if(e.hp<=0){s.score+=e.score;s.kills++;if(netHost()){s.teamXp=(s.teamXp||0)+e.xp;gainXP(e.xp)}else s.loot.push({x:e.x,y:e.y,type:'xp',value:e.xp});if(Math.random()<(e.type==='boss'?DATA.loot.bossHealChance:DATA.loot.healChance))s.loot.push({x:e.x+15,y:e.y,type:'heal',value:30});if(e.type==='boss'){s.bossDefeated=true;toast('Босс повержен · +1 000 очков')}particles(e.x,e.y,'#c9bd83',7)}}s.enemies=s.enemies.filter(e=>e.hp>0);transition();for(let l of s.loot){let collector=netHost()?closestParty(l.x,l.y):s;if(!collector)continue;let dx=collector.x-l.x,dy=collector.y-l.y,d=Math.hypot(dx,dy);if(d<135&&l.type==='xp'){l.x+=dx*dt*6;l.y+=dy*dt*6}if(d<25){if(l.type==='xp')gainXP(l.value);else{collector.hp=Math.min(collector.maxHp,collector.hp+l.value);sound(650,.1);particles(collector.x,collector.y,'#a6d69b',8)}l.collected=true}}s.loot=s.loot.filter(l=>!l.collected);if(s.loot.length>700){let xp=s.loot.filter(l=>l.type==='xp');if(xp.length>500){let first=xp[0];for(let l of xp.slice(1,150)){first.value+=l.value;l.collected=true}s.loot=s.loot.filter(l=>!l.collected)}}for(let p of s.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}s.particles=s.particles.filter(p=>p.life>0);saveTimer+=dt;if(saveTimer>8){saveTimer=0;saveRun()}if(s.pending)offer();hud()}
function hud(){let s=state,h=DATA.heroes[s.hero];$('hudHero').textContent=h.name+' · '+h.class.split(' · ')[1];$('hpFill').style.width=Math.max(0,s.hp/s.maxHp*100)+'%';$('hpText').textContent=Math.ceil(s.hp)+' / '+s.maxHp+' HP';$('hudLocation').textContent=DATA.locations[s.stage%5].name;$('hudCycle').textContent=difficulty().name.toUpperCase()+' · КРУГ '+(Math.floor(s.stage/5)+1)+' · '+Math.floor(s.time/60)+':'+String(Math.floor(s.time%60)).padStart(2,'0');$('hudScore').textContent=s.score.toLocaleString('ru');$('xpFill').style.width=s.xp/s.nextXp*100+'%';$('hudLevel').textContent='УРОВЕНЬ '+s.level+' · '+s.xp+' / '+s.nextXp+' XP';$('equipment').textContent=difficulty().name+' · '+s.weapon+' / '+s.armor+' · Следующий мир: '+((s.stage+1)*5000).toLocaleString('ru')+(s.score>=(s.stage+1)*5000&&!s.bossDefeated?' · победи босса':'');let b=s.enemies.find(e=>e.type==='boss');$('bossHud').classList.toggle('hidden',!b);if(b){$('bossName').textContent=b.name;$('bossFill').style.width=Math.max(0,b.hp/b.maxHp*100)+'%'}}
function toast(t){$('toast').textContent=t;$('toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.opacity=0,2600)}
function resize(){W=innerWidth;H=innerHeight;let d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);ctx.imageSmoothingEnabled=false}window.addEventListener('resize',resize);
function hash(x,y){let n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n)}
function draw(){if(!state)return;let s=state,l=DATA.locations[s.stage%5];ctx.fillStyle=l.color;ctx.fillRect(0,0,W,H);ctx.save();let shake=prefs.shake&&s.invuln>.55?4:0;ctx.translate(W/2-s.x+(Math.random()-.5)*shake,H/2-s.y+(Math.random()-.5)*shake);drawTerrain();
for(let o of s.loot){if(o.type==='heal')sprite(ctx,3,o.x,o.y,35);else{ctx.fillStyle='#a5dcca';ctx.beginPath();ctx.moveTo(o.x,o.y-5);ctx.lineTo(o.x+4,o.y);ctx.lineTo(o.x,o.y+5);ctx.lineTo(o.x-4,o.y);ctx.closePath();ctx.fill()}}
let objects=nearbyWorld(s.x,s.y,Math.max(W,H)*.65+180).obstacles.map(o=>({y:o.y,kind:'obstacle',o}));for(let e of s.enemies){if(Math.abs(e.x-s.x)<W/2+180&&Math.abs(e.y-s.y)<H/2+180)objects.push({y:e.y,kind:'enemy',o:e})}for(let a of Object.values(s.allies||{}))objects.push({y:a.y,kind:'ally',o:a});objects.push({y:s.y,kind:'hero'});objects.sort((a,b)=>a.y-b.y);for(let o of objects){if(o.kind==='obstacle')drawObstacle(o.o);else if(o.kind==='enemy')drawEnemy(o.o);else if(o.kind==='ally')drawAlly(o.o);else drawHero()}
for(let p of coopRenderedProjectiles()){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(p.vy,p.vx));if(p.hostile||p.splash){ctx.fillStyle=p.hostile?'#dd7978':p.kind==='violet'?'#bd8bff':'#f6bd70';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(0,0,p.hostile?7:p.kind==='violet'?9:5,0,7);ctx.fill();if(p.kind==='violet'){ctx.fillStyle='#ede0ff';ctx.beginPath();ctx.arc(0,0,3,0,Math.PI*2);ctx.fill()}}else if(p.kind==='daggers'){ctx.rotate(s.time*18);ctx.fillStyle='#d2cce3';ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-3,-3);ctx.lineTo(-3,3);ctx.closePath();ctx.fill();ctx.fillStyle='#92799a';ctx.fillRect(-9,-1,6,2)}else{ctx.strokeStyle='#dfdab6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-13,0);ctx.lineTo(7,0);ctx.lineTo(1,-4);ctx.moveTo(7,0);ctx.lineTo(1,4);ctx.stroke()}ctx.restore()}
for(let p of s.particles){ctx.fillStyle=p.color;ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1;drawAim();ctx.restore();let grad=ctx.createRadialGradient(W/2,H/2,H*.2,W/2,H/2,Math.max(W,H)*.65);grad.addColorStop(0,'#0000');grad.addColorStop(1,'#050c0c88');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H)}
function frame(t){let dt=Math.min((t-last)/1000,.05);last=t;if(mode==='playing'){if(netGuest())updateGuest(dt);else update(dt);}if(mode!=='menu')draw();requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{let k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(k)&&mode!=='menu')e.preventDefault();keys[k]=true;if(!e.repeat&&(k==='Escape'||k==='p')){if(mode==='playing')pause();else if(mode==='paused'){mode='playing';closeDialog()}}});window.addEventListener('keyup',e=>keys[e.key.length===1?e.key.toLowerCase():e.key]=false);window.addEventListener('blur',()=>{clearMovement();if(mode==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause()});window.addEventListener('beforeunload',()=>{if(state&&mode!=='dead')saveRun()});
let joyPointer=null;const joy=$('joystick');function joyMove(e){let r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy),max=34;if(d>max){dx*=max/d;dy*=max/d}stick={x:dx/max,y:dy/max};joy.firstElementChild.style.transform=`translate(${dx}px,${dy}px)`}joy.onpointerdown=e=>{joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e)};joy.onpointermove=e=>{if(e.pointerId===joyPointer)joyMove(e)};joy.onpointerup=joy.onpointercancel=()=>{joyPointer=null;stick={x:0,y:0};joy.firstElementChild.style.transform=''};
$('start').onclick=()=>{if(saves[slot]){dialog(`<h2>Новое странствие?</h2><p>Сохранение в слоте ${slot+1} будет заменено. Можно продолжить его или выбрать другой слот.</p><button class="primary" id="confirmNew">Начать заново</button><button class="secondary" id="continueOld">Продолжить сохранение</button><button class="secondary" id="cancelNew">Отмена</button>`);$('confirmNew').onclick=()=>begin();$('continueOld').onclick=()=>begin(true);$('cancelNew').onclick=closeDialog()}else begin()};$('saveBtn').onclick=saveMenu;$('settingsBtn').onclick=()=>settings();$('pauseBtn').onclick=pause;
atlas.onload=()=>{spriteAtlas=transparentAtlas(atlas);if(DATA)renderMenu()};atlas.src='atlas.png';loadHeroAnimations();loadEnvironment();loadSorcerer();
$('difficulty').onchange=e=>{prefs.difficulty=e.target.value;persist();$('difficultyHint').textContent=difficulty().description};
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||e.pointerType==='pen'){let r=canvas.getBoundingClientRect();aim={x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height,active:true};$('game').classList.add('aiming')}});
canvas.addEventListener('pointerleave',()=>{aim.active=false;$('game').classList.remove('aiming')});
let aimPointer=null;const aimJoy=$('aimJoystick');function aimMove(e){let r=aimJoy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy),max=34;if(d>max){dx*=max/d;dy*=max/d}if(d>5){touchAim={angle:Math.atan2(dy,dx),active:true};aim.active=false}aimJoy.firstElementChild.style.transform=`translate(${dx}px,${dy}px)`}aimJoy.onpointerdown=e=>{aimPointer=e.pointerId;aimJoy.setPointerCapture(e.pointerId);aimMove(e)};aimJoy.onpointermove=e=>{if(e.pointerId===aimPointer)aimMove(e)};aimJoy.onpointerup=aimJoy.onpointercancel=()=>{aimPointer=null;touchAim.active=false;aimJoy.firstElementChild.style.transform=''};
fetch('data.json?v=4').then(r=>{if(!r.ok)throw Error('data');return r.json()}).then(data=>{DATA=data;renderMenu();$('start').disabled=false;$('start').innerHTML='Начать странствие <span>↗</span>';$('saveBtn').disabled=false;$('difficulty').disabled=false;resize();initCoop();requestAnimationFrame(frame)}).catch(()=>{$('start').disabled=true;$('start').textContent='Не удалось загрузить игру. Обновите страницу.'});
