'use strict';
// Continuous rig animation supplements painted sprites with intermediate poses.
const SHOT_COLORS={arrow:'#ecd3a0',thorn:'#a9d088',venom:'#b7e768',ice:'#8ee9ff',fire:'#ff9862',void:'#c495ff'};
const motionSteer=steerEnemy;
steerEnemy=function(e,dx,dy,dt){if(!e.ranged)return motionSteer(e,dx,dy,dt);let distance=Math.hypot(dx,dy);if(e.castWind>0)return 0;if(distance<180)return motionSteer(e,-dx,-dy,dt);if(distance<340)return 0;return motionSteer(e,dx,dy,dt)};
const motionUpdate=update;
update=function(dt){for(let e of state.enemies){if(!e.ranged||e.hp<=0)continue;let target=netHost()?closestParty(e.x,e.y):state;if(!target)continue;let d=Math.hypot(target.x-e.x,target.y-e.y);if(e.castWind>0){e.castWind=Math.max(0,e.castWind-dt);if(e.castWind===0){let a=e.castAngle,v=(e.weaponKind==='bow'?300:225)*(difficulty().id==='hard'?1.18:difficulty().id==='medium'?1.08:1),kind=e.shotKind||'thorn';for(let j=0;j<(kind==='void'?3:1);j++){let angle=a+(j-((kind==='void'?3:1)-1)/2)*.16;state.projectiles.push({x:e.x+Math.cos(angle)*23,y:e.y+Math.sin(angle)*23,vx:Math.cos(angle)*v,vy:Math.sin(angle)*v,life:3,hostile:true,damage:e.damage*.7,color:SHOT_COLORS[kind],shotKind:kind})}e.attackAnim=.3;e.rangedTimer=(e.weaponKind==='bow'?2.5:3.4)*(difficulty().id==='hard'?.7:difficulty().id==='medium'?.85:1)}}else{e.rangedTimer=(e.rangedTimer??2)-dt;if(e.rangedTimer<=0&&d<650){e.castWind=.65;e.castAngle=Math.atan2(target.y-e.y,target.x-e.x)}}}motionUpdate(dt)};
const motionHero=drawHero;
drawHero=function(){let s=state,clock=s.walkClock||0,attack=s.attackAnim||0;ctx.save();ctx.translate(s.x,s.y);ctx.transform(1,0,s.moving?Math.sin(clock*12)*.018:0,1,0,0);ctx.translate(-s.x,-s.y);motionHero();ctx.restore();if(attack>0){let a=s.aimAngle||0,release=Math.sin((1-attack/.3)*Math.PI);ctx.save();ctx.translate(s.x,s.y-4);ctx.rotate(a);for(let side of [-1,1]){ctx.strokeStyle=DATA.heroes[s.hero].color;ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(4,side*7);ctx.lineTo(12-release*4,side*5);ctx.lineTo(21-release*7,side*3);ctx.stroke()}ctx.restore()}};
// Twelve interpolated poses between each of the four painted keyframes.
const keyframeSprite=animatedHeroSprite;
animatedHeroSprite=function(c,hero,frame,attack,x,y,size){if(!state||c!==ctx){keyframeSprite(c,hero,frame,attack,x,y,size);return}let s=state,phase=attack?Math.max(0,Math.min(3.999,(.3-(s.attackAnim||0))/.075)):s.moving?((s.walkClock||0)*9)%4:0,base=Math.floor(phase),blend=Math.round((phase-base)*12)/12;c.save();let alpha=c.globalAlpha;keyframeSprite(c,hero,base,attack,x,y,size);if(blend>0){c.globalAlpha=alpha*blend*.45;keyframeSprite(c,hero,(base+1)%4,attack,x,y,size)}c.restore()};
const paintedFallback=drawEnemy;
drawEnemy=function(e){if(!e.spec||!enemyDetailAtlas){paintedFallback(e);return}let c=ctx,clock=(e.walkClock||0)*12+(e.phase||0),walk=Math.sin(clock),attack=e.castWind>0?1-e.castWind/.65:e.attackAnim>0?1-e.attackAnim/.3:0,recoil=Math.sin(attack*Math.PI),form=e.atlasForm??e.form,index=e.theme*4+form,rect=enemyDetailRects[index],size=e.type==='mini'?108:78,scale=size/rect[3],dw=rect[2]*scale,bob=Math.abs(walk)*1.7;ellipse(c,e.x,e.y+18,e.type==='mini'?26:18,6,'#0006');c.save();c.translate(e.x,e.y-bob);c.scale(Math.cos(e.angle||0)<0?-1:1,1);c.rotate(walk*.022-recoil*.05);if(e.hitAnim>0)c.globalAlpha=.55;let strip=rect[3]/12;for(let i=0;i<12;i++){let lower=i>=8,offset=lower?Math.sin(clock+(i-8)*.25)*2.6:Math.sin(clock+i*.12)*.35-recoil*(i<7?2:0);c.drawImage(enemyDetailAtlas,rect[0],rect[1]+i*strip,rect[2],strip, -dw/2+offset,-size+22+i*size/12,dw,size/12+.5)}c.restore();let a=e.castWind>0?e.castAngle:e.angle||0;drawWeapon(e.x,e.y,a,e.weaponKind||(e.ranged?'staff':'daggers'),e.castWind>0?.3*(1-e.castWind/.65):e.attackAnim||0,true);if(e.castWind>0){let color=SHOT_COLORS[e.shotKind]||'#efd086',progress=1-e.castWind/.65;c.save();c.strokeStyle=color;c.globalAlpha=.35+progress*.45;c.lineWidth=1.5;c.setLineDash([4,6]);c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.x+Math.cos(a)*115,e.y+Math.sin(a)*115);c.stroke();c.setLineDash([]);ellipse(c,e.x+Math.cos(a)*24,e.y+Math.sin(a)*24,3+progress*5,3+progress*5,color);c.restore()}if(e.attackWind>0){c.strokeStyle='#e4bc7b';c.lineWidth=2;c.beginPath();c.arc(e.x,e.y,e.radius+8,0,Math.PI*2);c.stroke()}if(e.hp<e.maxHp){c.fillStyle='#000a';c.fillRect(e.x-20,e.y-size+14,40,3);c.fillStyle=THEMES[e.theme].trap;c.fillRect(e.x-20,e.y-size+14,40*Math.max(0,e.hp/e.maxHp),3)}};
const projectileDraw=draw;
draw=function(){projectileDraw();if(!state)return;ctx.save();ctx.translate(W/2-state.x,H/2-state.y);for(let p of state.projectiles){if(!p.hostile||!p.shotKind)continue;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(p.vy,p.vx));ctx.strokeStyle=p.color;ctx.fillStyle=p.color;ctx.lineWidth=2;if(p.shotKind==='arrow'||p.shotKind==='thorn'){ctx.beginPath();ctx.moveTo(-17,0);ctx.lineTo(9,0);ctx.lineTo(3,-4);ctx.moveTo(9,0);ctx.lineTo(3,4);ctx.stroke()}else{ctx.globalAlpha=.5;ctx.beginPath();ctx.moveTo(-22,0);ctx.lineTo(-3,-5);ctx.lineTo(4,0);ctx.lineTo(-3,5);ctx.closePath();ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#f2e8d8';ellipse(ctx,0,0,2,2,'#f2e8d8')}ctx.restore()}ctx.restore()};
