'use strict';
let net=null,netTimer=null,netPredicted=[];
function netActive(){return !!net}
function netGuest(){return !!net&&net.hostId!==net.playerId&&net.started}
function netHost(){return !!net&&net.hostId===net.playerId&&net.started}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function coopRequest(body,session=net){let controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{let r=await fetch(window.VEILBOUND_COOP_API,{method:'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.token}:{})},body:JSON.stringify(body),signal:controller.signal});let data;try{data=await r.json()}catch{throw Error('Сервер недоступен. Откройте опубликованную версию игры.')}if(!r.ok)throw Error(data.error||'Не удалось связаться с лобби.');return data}finally{clearTimeout(timer)}}
function coopMenu(initial=''){if(!window.VEILBOUND_COOP_API){dialog('<h2>Сервер кооператива ещё не подключён</h2><p>Одиночная игра доступна. Для совместной игры требуется отдельный сервер лобби.</p><button class="primary" id="coopBack">Назад</button>');$('coopBack').onclick=closeDialog;return}if(net){showLobby();return}dialog(`<div class="eyebrow">ВМЕСТЕ ПРОТИВ СУМЕРЕК · 2–4 ИГРОКА</div><h2>Сетевой кооператив</h2><label>Твоё имя <input id="coopName" maxlength="20" placeholder="Странник" value="${escapeHTML(prefs.playerName||'')}"></label><label>Персонаж <select id="coopHero">${DATA.heroes.map((h,i)=>`<option value="${i}" ${i===selected?'selected':''}>${h.name} — ${h.class}</option>`).join('')}</select></label><p>Общие враги, счёт и опыт. Улучшения выбирает каждый игрок. Создатель лобби держит игру открытой и управляет общей паузой.</p><button class="primary" id="createCoop">Создать лобби · ${difficulty().name}</button><label>Код или ссылка <input id="coopCode" placeholder="Например, AB3K7M" value="${escapeHTML(initial)}"></label><button class="secondary" id="joinCoop">Присоединиться</button><p id="coopError" class="error" role="status"></p><button class="quiet" id="coopBack">Назад</button>`);$('coopBack').onclick=closeDialog;$('createCoop').onclick=()=>connectCoop('create');$('joinCoop').onclick=()=>connectCoop('join')}
function extractCode(value){try{let u=new URL(value);value=u.searchParams.get('lobby')||value}catch{}return value.trim().toUpperCase()}
async function connectCoop(action){let name=$('coopName').value.trim()||'Странник',hero=+$('coopHero').value,code=extractCode($('coopCode').value);$('createCoop').disabled=true;$('joinCoop').disabled=true;$('coopError').textContent='Подключение…';try{let room=await coopRequest({action,name,hero,code,difficulty:prefs.difficulty},null);prefs.playerName=name;persist();selected=hero;net={...room,token:room.token,started:false,busy:false,seq:0,events:[],frame:0,lastFrame:-1,lastSuccess:Date.now(),errors:0,receivedXp:0};netPredicted=[];showLobby();scheduleNet()}catch(e){$('coopError').textContent=e.message;$('createCoop').disabled=false;$('joinCoop').disabled=false}}
function showLobby(){if(!net)return;let host=net.playerId===net.hostId,link=location.origin+location.pathname+'?lobby='+net.code;dialog(`<div class="eyebrow">${host?'ТВОЁ ЛОББИ':'ТЫ В ЛОББИ'} · ${DATA.difficulties.find(d=>d.id===net.difficulty).name}</div><h2>Собери отряд</h2><div class="lobbyCode"><small>КОД ПРИГЛАШЕНИЯ</small><strong>${net.code}</strong></div><div id="lobbyMembers"></div><label>Ссылка приглашения <input id="lobbyLink" readonly value="${escapeHTML(link)}"></label><button id="copyLobby" class="secondary">Скопировать ссылку</button><p id="lobbyStatus" role="status">${host?'Пригласи друга и начни странствие.':'Ожидаем начала игры от создателя.'}</p>${host?'<button class="primary" id="startCoop">Начать вместе →</button>':''}<button class="quiet" id="leaveLobby">Выйти из лобби</button>`);$('copyLobby').onclick=async()=>{try{await navigator.clipboard.writeText(link);$('copyLobby').textContent='Ссылка скопирована'}catch{$('lobbyLink').select();$('copyLobby').textContent='Скопируйте выделенную ссылку'}};$('leaveLobby').onclick=()=>{leaveCoop();closeDialog();renderMenu()};if(host)$('startCoop').onclick=startCoop;renderLobbyMembers()}
function renderLobbyMembers(){if(!net||!$('lobbyMembers'))return;$('lobbyMembers').innerHTML=net.members.map(m=>`<div class="lobbyMember"><span>✦</span><div><b>${escapeHTML(m.name)} ${m.id===net.hostId?'· создатель':''}</b><small>${DATA.heroes[m.hero].name} · ${DATA.heroes[m.hero].class}</small></div></div>`).join('');if(net.playerId===net.hostId&&$('startCoop'))$('startCoop').disabled=net.members.length<2}
async function startCoop(){if(!net)return;$('startCoop').disabled=true;try{let room=await coopRequest({action:'start',code:net.code});Object.assign(net,room);startNetworkGame()}catch(e){$('lobbyStatus').textContent=e.message;$('startCoop').disabled=false}}
function startNetworkGame(){if(net.started)return;let member=net.members.find(m=>m.id===net.playerId);selected=member.hero;prefs.difficulty=net.difficulty;net.started=true;net.receivedXp=0;begin(false);state.teamXp=0;state.allies={};state.down=false;state.netAppliedXp=0;state.spawnTimer=.2;state.netRoom=net.code;netPredicted=[];if(netHost())syncAllies(net.members);$('netStatus').classList.remove('hidden');$('netStatus').textContent='ЛОББИ '+net.code+' · '+net.members.length+'/4';if(netGuest())toast('Ожидаем мир от создателя…')}
function actorFromMember(m){let h=DATA.heroes[m.hero];return {id:m.id,name:m.name,hero:m.hero,x:state.x+35,y:state.y+35,targetX:state.x+35,targetY:state.y+35,hp:h.hp,maxHp:h.hp,speed:h.speed,damage:h.damage,cooldown:h.cooldown,pierce:h.pierce||1,splash:h.splash||0,crit:h.crit||0,multi:1,weapon:h.weapon,armor:h.armor,armorReduction:0,upgrades:{},level:1,invuln:1,walkClock:0,attackAnim:0,aimAngle:0,attackCount:0,attackSeq:0,moving:false,down:false}}
function syncAllies(members){if(!state||!netHost())return;let ids=new Set();for(let m of members){if(m.id===net.playerId)continue;ids.add(m.id);let a=state.allies[m.id]||(state.allies[m.id]=actorFromMember(m)),p=m.payload||{};if(p.stage!==undefined&&p.stage!==state.stage)continue;if(Number.isFinite(p.x)&&Number.isFinite(p.y)){a.targetX=p.x;a.targetY=p.y}a.aimAngle=Number.isFinite(p.angle)?p.angle:a.aimAngle;let stats=p.stats;if(stats&&stats.weapon){let healthDelta=(stats.upgrades?.health||0)-(a.upgrades?.health||0);if(healthDelta>0&&!a.down)a.hp=Math.min(stats.maxHp,a.hp+35*healthDelta);for(let k of ['level','maxHp','speed','damage','cooldown','pierce','splash','crit','multi','weapon','armor','armorReduction','upgrades'])a[k]=stats[k]??a[k];a.hp=Math.min(a.hp,a.maxHp)}for(let event of p.events||[]){if(event.seq<=a.attackSeq)continue;a.attackSeq=event.seq;if(!a.down)fireAlly(a,event.angle,event.seq)}}for(let id of Object.keys(state.allies))if(!ids.has(id))delete state.allies[id]}
function fireAlly(a,angle,seq){a.attackAnim=.3;a.attackCount++;let kind=weaponKind(a);for(let i=0;i<a.multi;i++){let dir=angle+(i-(a.multi-1)/2)*.12;state.projectiles.push({x:a.x+Math.cos(dir)*22,y:a.y+Math.sin(dir)*22,vx:Math.cos(dir)*550,vy:Math.sin(dir)*550,life:2.2,damage:a.damage*(a.crit&&a.attackCount%a.crit===0?2:1),pierce:a.pierce,splash:a.splash,hit:[],hostile:false,kind,color:DATA.heroes[a.hero].color,owner:a.id,eventSeq:seq})}}
function netShot(angle){if(!net)return null;let seq=++net.seq;if(netGuest()){net.events.push({seq,angle});if(net.events.length>24)net.events.splice(0,net.events.length-24)}return seq}
function netParty(){return [state,...Object.values(state.allies||{})].filter(p=>p.hp>0&&!p.down)}
function closestParty(x,y){let best=null,d=Infinity;for(let p of netParty()){let dist=(p.x-x)**2+(p.y-y)**2;if(dist<d){d=dist;best=p}}return best}
function hurtParty(actor,damage){if(actor===state){hurt(damage);return}if(actor.invuln>0||actor.down)return;actor.hp=Math.max(0,actor.hp-damage*(1-actor.armorReduction));actor.invuln=.7;particles(actor.x,actor.y,'#ef8f89',8);if(actor.hp<=0)actor.down=true}
function updateAllies(dt){if(!netHost())return;for(let a of Object.values(state.allies||{})){a.invuln=Math.max(0,a.invuln-dt);a.attackAnim=Math.max(0,a.attackAnim-dt);if(a.down)continue;let dx=a.targetX-a.x,dy=a.targetY-a.y,d=Math.hypot(dx,dy),step=Math.min(d,a.speed*dt*1.12);let moved=d>.1?moveActor(a,dx/d*step,dy/d*step):0;a.moving=moved>.1;a.walkClock+=moved/a.speed;for(let t of nearbyWorld(a.x,a.y,65).traps){if(Math.hypot(a.x-t.x,a.y-t.y)<t.r+10&&trapPhase(t).active)hurtParty(a,THEMES[t.theme].damage*difficulty().damage)}}}
function packWorld(){let s=state;let players=[{...s,id:net.playerId,name:prefs.playerName||'Странник'},...Object.values(s.allies||{})].map(p=>Object.fromEntries(['id','name','hero','x','y','hp','maxHp','down','level','walkClock','moving','attackAnim','aimAngle','attackSeq'].map(k=>[k,p[k]??(k==='attackSeq'?net.seq:0)])));return {score:s.score,kills:s.kills,time:s.time,stage:s.stage,teamXp:s.teamXp||0,players,enemies:s.enemies.map(e=>Object.fromEntries(['id','x','y','hp','maxHp','sprite','type','name','radius','phase','angle','walkClock','attackWind','attackAnim','hitAnim','shot','spec','theme','form','atlasForm','ranged','weaponKind','shotKind','castWind','castAngle','bossArt','bossIndex','attack','aoe','aoeWind'].map(k=>[k,e[k]]))),projectiles:s.projectiles.slice(-220),loot:s.loot.slice(-300),bossSpawned:s.bossSpawned,bossDefeated:s.bossDefeated,bossTimer:s.bossTimer,bossKills:s.bossKills,bossHazards:s.bossHazards,paused:mode==='paused'||mode==='upgrade',finished:mode==='dead'}}
function applyWorld(world){if(!world||!Array.isArray(world.players))return;let s=state,stageChanged=s.stage!==world.stage,old=new Map(s.enemies.map(e=>[e.id,e]));s.score=world.score;s.kills=world.kills||0;s.time=world.time;if(stageChanged){s.stage=world.stage;resetWorld();netPredicted=[]}s.enemies=(world.enemies||[]).map(e=>{let before=old.get(e.id);return {...e,targetX:e.x,targetY:e.y,x:before&&!stageChanged?before.x:e.x,y:before&&!stageChanged?before.y:e.y}});s.projectiles=world.projectiles||[];s.loot=world.loot||[];s.bossSpawned=world.bossSpawned;s.bossDefeated=world.bossDefeated;s.bossTimer=world.bossTimer;s.bossKills=world.bossKills||0;s.bossHazards=world.bossHazards||[];s.netPaused=world.paused;let self=world.players.find(p=>p.id===net.playerId);if(self){if(stageChanged||Math.hypot(self.x-s.x,self.y-s.y)>160){s.x=self.x;s.y=self.y}s.hp=self.hp;s.down=self.down;net.events=net.events.filter(e=>e.seq>(self.attackSeq||0));netPredicted=netPredicted.filter(p=>p.eventSeq>(self.attackSeq||0))}s.allies=Object.fromEntries(world.players.filter(p=>p.id!==net.playerId).map(p=>[p.id,p]));let xp=Math.max(0,(world.teamXp||0)-net.receivedXp);net.receivedXp=world.teamXp||0;if(xp)gainXP(xp);if(s.pending&&mode==='playing')offer();if(world.finished&&mode!=='dead'){mode='playing';die()}hud()}
function playerPayload(){if(!state)return {};let s=state,stats=Object.fromEntries(['level','maxHp','speed','damage','cooldown','pierce','splash','crit','multi','weapon','armor','armorReduction','upgrades','upgradeRarities','regen','magnetBonus','focusBonus','skinBoost','critChance'].map(k=>[k,s[k]]));return {x:s.x,y:s.y,stage:s.stage,angle:s.aimAngle,paused:mode!=='playing',stats,events:net.events}}
function scheduleNet(){clearTimeout(netTimer);netTimer=setTimeout(netTick,net?.started?220:650)}
async function netTick(){if(!net)return;let session=net;if(session.busy){scheduleNet();return}session.busy=true;try{let body={action:'sync',code:session.code,player:playerPayload()};if(netHost()&&state){body.snapshot=packWorld();body.frame=++net.frame;body.finished=mode==='dead'}let room=await coopRequest(body,session);if(net!==session)return;session.lastSuccess=Date.now();session.errors=0;session.members=room.members;session.status=room.status;if(!session.started&&(room.status==='running'||room.status==='finished'))startNetworkGame();if(session.started){if(netHost())syncAllies(room.members);else if(room.frame>session.lastFrame){session.lastFrame=room.frame;applyWorld(room.snapshot)}$('netStatus').textContent='ЛОББИ '+session.code+' · '+session.members.length+'/4'+(state?.netPaused?' · ОБЩАЯ ПАУЗА':'')}else renderLobbyMembers()}catch(e){if(net!==session)return;session.errors++;let status=state?$('netStatus'):$('lobbyStatus');if(status)status.textContent=e.message;if(session.errors>=8){if(state){mode='paused';dialog(`<h2>Связь потеряна</h2><p>${escapeHTML(e.message)}</p><button class="primary" id="netExit">Вернуться в меню</button>`);$('netExit').onclick=menu}else{dialog(`<h2>Лобби недоступно</h2><p>${escapeHTML(e.message)}</p><button class="primary" id="netExit">Назад</button>`);$('netExit').onclick=()=>{leaveCoop();closeDialog()}}clearTimeout(netTimer);session.stopped=true;session.busy=false;return}}finally{session.busy=false;if(net===session&&!session.stopped)scheduleNet()}}
function leaveCoop(){let session=net;net=null;netPredicted=[];clearTimeout(netTimer);$('netStatus').classList.add('hidden');if(session)coopRequest({action:'leave',code:session.code},session).catch(()=>{});try{let u=new URL(location.href);u.searchParams.delete('lobby');history.replaceState(null,'',u)}catch{}}
function updateGuest(dt){let s=state;if(!s.netPaused&&!s.down){let mx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0)+stick.x,my=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0)+stick.y,len=Math.hypot(mx,my);if(len>1){mx/=len;my/=len}let moved=moveActor(s,mx*s.speed*dt,my*s.speed*dt);s.moving=moved>.1;s.walkClock+=moved/s.speed;s.aimAngle=aimDirection();s.attackAnim=Math.max(0,s.attackAnim-dt);s.attackTimer-=dt;if(s.attackTimer<=0){shoot();s.attackTimer=s.cooldown}}else s.moving=false;for(let e of s.enemies){if(!s.netPaused){e.x+=(e.targetX-e.x)*Math.min(1,dt*12);e.y+=(e.targetY-e.y)*Math.min(1,dt*12);e.walkClock=(e.walkClock||0)+dt;e.attackAnim=Math.max(0,(e.attackAnim||0)-dt)}}if(!s.netPaused){for(let p of [...s.projectiles,...netPredicted]){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(isBlocked(p.x,p.y,4))p.life=0}netPredicted=netPredicted.filter(p=>p.life>0);s.projectiles=s.projectiles.filter(p=>p.life>0)}hud()}
function coopRenderedProjectiles(){return netGuest()?[...state.projectiles,...netPredicted]:state.projectiles}
function drawAlly(a){if(a.down){ctx.save();ctx.globalAlpha=.45;ctx.strokeStyle='#d7b3a2';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x-8,a.y-8);ctx.lineTo(a.x+8,a.y+8);ctx.moveTo(a.x+8,a.y-8);ctx.lineTo(a.x-8,a.y+8);ctx.stroke();ctx.restore();return}let saved=state;try{state={...a,time:saved.time,invuln:a.invuln||0};drawHero()}finally{state=saved}ctx.fillStyle='#e5e1c9';ctx.font='10px Arial';ctx.textAlign='center';ctx.fillText(a.name,a.x,a.y-40);ctx.fillStyle='#0009';ctx.fillRect(a.x-18,a.y-34,36,3);ctx.fillStyle='#a7c994';ctx.fillRect(a.x-18,a.y-34,36*Math.max(0,a.hp/a.maxHp),3)}
function initCoop(){ $('coopBtn').disabled=false;$('coopBtn').onclick=()=>coopMenu();let code=new URL(location.href).searchParams.get('lobby');if(code)coopMenu(code)}
