'use strict';
const UPGRADE_LIMITS={common:5,rare:4,epic:3,legendary:2};
function learnedRarity(s,id){return RARITIES.find(r=>r.id===s.upgradeRarities?.[id])}
function upgradeLimit(s,u){return UPGRADE_LIMITS[(learnedRarity(s,u.id)||u.rarity||RARITIES[0]).id]}
function availableUpgrade(s,u){if((s.upgrades[u.id]||0)>=upgradeLimit(s,u))return false;return !(u.id==='multi'&&s.multi>=6)&&!(u.id==='plate'&&s.armorReduction>=.3)&&!(u.id==='cloak'&&s.cloakBonus)&&!(u.weapon&&s.weapon===u.name)}
const CAMP_REWARDS=[{id:'restHeal',name:'Глоток жизни',icon:'♡',type:'Поддержка',description:'Восстанавливает 30 HP. Максимум здоровья не растёт.'},{id:'restWard',name:'Краткая защита',icon:'⬡',type:'Поддержка',description:'Защищает от урона на 3 секунды.'},{id:'restSkill',name:'Второе дыхание',icon:'ϟ',type:'Поддержка',description:'Сокращает оставшееся ожидание активной способности на 10 секунд.'}];
function upgradeChoices(s){let pool=DATA.upgrades.filter(u=>availableUpgrade(s,u)),result=[],hasWeapon=false;while(result.length<3&&pool.length){let weights=pool.map(u=>u.weapon?(hasWeapon?0:.15):1),sum=weights.reduce((a,b)=>a+b,0);if(!sum)break;let roll=Math.random()*sum,index=weights.findIndex(w=>(roll-=w)<0);if(index<0)index=weights.length-1;let u=pool.splice(index,1)[0],rarity=learnedRarity(s,u.id)||rollRarity();result.push({...u,rarity});if(u.weapon)hasWeapon=true}for(let reward of CAMP_REWARDS){if(result.length>=3)break;result.push({...reward,reward:true})}return result}
offer=function(){if(!state.pending){mode='playing';closeDialog();return}mode='upgrade';choices=upgradeChoices(state);dialog(`<div class="eyebrow">НОВАЯ СИЛА · УРОВЕНЬ ${state.level}</div><h2>Выбери свой путь</h2><p>Лимиты: обычная 5 · редкая 4 · эпическая 3 · легендарная 2.<br>Полностью изученный талант можно возвысить до следующей редкости.</p><div class="upgradeGrid">${choices.map((u,i)=>{let color=u.rarity?.color||'#b7c89d',count=state.upgrades[u.id]||0;return `<button class="upgrade" style="border-color:${color}" data-up="${i}"><span style="color:${color}">${u.icon}</span><small style="color:${color}">${u.reward?'Поддержка':u.promotion?'Повышение редкости':u.rarity.name+' · '+u.type}</small><b>${u.promotion?'Возвышение: ':''}${u.name}</b><p>${u.reward?u.description:u.promotion?'Повышает редкость до «'+u.rarity.name+'». Все полученные бонусы сохраняются; открываются новые уровни.':rarityDescription(u)}</p><small>${u.reward?'Когда изученные улучшения недоступны':u.promotion?'Предыдущая редкость изучена полностью':`Изучено ${count}/${UPGRADE_LIMITS[u.rarity.id]} · выбор ${count+1}/${UPGRADE_LIMITS[u.rarity.id]}`}</small></button>`}).join('')}</div>`);document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>choose(choices[+b.dataset.up]))};
const limitedChoose=choose;choose=function(u){if(!state.pending)return;if(u.reward){if(!CAMP_REWARDS.some(r=>r.id===u.id))return;if(u.id==='restHeal')state.hp=Math.min(state.maxHp,state.hp+30);if(u.id==='restWard')state.invuln=Math.max(state.invuln,3);if(u.id==='restSkill')state.skillCooldown=Math.max(0,(state.skillCooldown||0)-10);state.pending--;saveRun();offer();return}let spec=DATA.upgrades.find(r=>r.id===u.id);if(!spec)return;let rarity=learnedRarity(state,u.id)||u.rarity||RARITIES[0];u={...spec,rarity};if(!availableUpgrade(state,u)){offer();return}state.upgradeRarities??={};state.upgradeRarities[u.id]=rarity.id;limitedChoose(u)};
const cappedState=newState;newState=function(){let s=cappedState();s.upgradeRarities={};return s};
const cappedMigrate=migrateState;migrateState=function(s){cappedMigrate(s);s.upgradeRarities??={};for(let [id,count] of Object.entries(s.upgrades||{}))if(count>0&&!s.upgradeRarities[id])s.upgradeRarities[id]='common'};
